-- LAST - 

DROP TABLE TR_SCORE;
DROP TABLE SEAT;
DROP TABLE STUDY;
DROP TABLE F_BOARD;
DROP TABLE N_BOARD;
DROP  TABLE T_BOARD;
DROP  TABLE T_REPLY;
DROP  TABLE N_REPLY;
DROP  TABLE F_REPLY;
DROP TABLE N_ATTACH; 
DROP TABLE F_ATTACH;
DROP TABLE T_ATTACH;
DROP TABLE S_ATTACH;
DROP TABLE  SEAT;
DROP TABLE CHATTING; 
DROP TABLE TR_SCORE;
DROP TABLE TR;


-- 시퀀스  -- 

DROP SEQUENCE SEQ_NBNO; 
DROP SEQUENCE SEQ_FBNO;
DROP SEQUENCE SEQ_TBNO;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_NAFID; 
DROP SEQUENCE SEQ_FAFID; 
DROP SEQUENCE SEQ_TAFID; 
DROP SEQUENCE SEQ_SAFID; 
DROP SEQUENCE SEQ_NRID;
DROP SEQUENCE SEQ_FRID;
DROP SEQUENCE SEQ_TRID;
DROP SEQUENCE SEQ_TRNO;
DROP SEQUENCE SEQ_SBNO;





CREATE SEQUENCE SEQ_NBNO;
--공지사항 시퀀스 
CREATE SEQUENCE SEQ_FBNO; 
--자유게시판 시퀀스 
CREATE SEQUENCE SEQ_TBNO; 
--사진게시판 시퀀스 

CREATE SEQUENCE  "SEQ_SCHEDULE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
-- 스케줄 시퀀스 
CREATE SEQUENCE  "SEQ_STUDY"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;   
-- 스터디시퀀스 
CREATE SEQUENCE  "SEQ_UNO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; 	    
-- 유저시퀀스
CREATE SEQUENCE  "SEQ_VACATION"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;   
--휴가시퀀스

CREATE SEQUENCE SEQ_NAFID;
-- 공지사항 첨부파일 시퀀스
CREATE SEQUENCE SEQ_FAFID; 
-- 자유게시판 첨부파일 시퀀스
CREATE SEQUENCE SEQ_TAFID; 
-- 사진게시판 첨부파일 시퀀스 
CREATE SEQUENCE SEQ_SAFID;
-- 공유자료 첨부파일 시퀀스 

CREATE SEQUENCE SEQ_SBNO;
-- 자료실 시퀀스 

CREATE SEQUENCE SEQ_NRID; 
-- 공지사항 리플 시퀀스 
CREATE SEQUENCE SEQ_FRID;  
-- 자유게시판 리플 시퀀스 	
CREATE SEQUENCE SEQ_TRID; 
-- 사진게시판 리플 시퀀스 
Create sequence SEQ_TRNO minvalue 1 maxvalue 10000 start with 1 increment by 1;
-- 맛집 시퀀스


-- 강현모 --
--------------------------------------------------------
--  DDL for Table APP_STUDY
--------------------------------------------------------

  CREATE TABLE "APP_STUDY" 
   (	"SID" NUMBER, 
	"USER_NO" NUMBER, 
	"APP_DATE" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APP_STUDY"."SID" IS '시퀀스';
   COMMENT ON COLUMN "APP_STUDY"."USER_NO" IS '시퀀스 적용';
--------------------------------------------------------
--  DDL for Table APP_VACATION
--------------------------------------------------------

  CREATE TABLE "APP_VACATION" 
   (	"VID" NUMBER, 
	"USER_NO" NUMBER, 
	"SID" NUMBER, 
	"APPR_YN" VARCHAR2(1 BYTE), 
	"APP_DATE" DATE DEFAULT SYSDATE, 
	"APPR_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APP_VACATION"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "APP_VACATION"."SID" IS '시퀀스적용';
--------------------------------------------------------
--  DDL for Table CLASS
--------------------------------------------------------

  CREATE TABLE "CLASS" 
   (	"CID" NUMBER, 
	"C_NAME" VARCHAR2(20 BYTE), 
	"TID" NUMBER, 
	"PERSONNEL" NUMBER, 
	"STR_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(3 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

   CREATE TABLE "KH"."MEMBER" 
   (	"USER_NO" NUMBER, 
	"CID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_PWD" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(15 BYTE), 
	"RRN" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"ENROLL_DATE" DATE, 
	"MODIFY_DATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"LEVEL" VARCHAR2(1 BYTE) DEFAULT '3', 
	"MAJOR" VARCHAR2(3 BYTE), 
	"SMOKING" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SEAT" VARCHAR2(3 BYTE), 
	"EXP" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CONSULT" VARCHAR2(200 BYTE), 
	"APPROVE" VARCHAR2(3 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "MEMBER"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."CID" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴여부';
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SCHEDULE" 
   (	"SID" NUMBER, 
	"CID" NUMBER, 
	"STID" NUMBER, 
	"SC_NAME" VARCHAR2(20 BYTE), 
	"STR_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCHEDULE"."SID" IS '시퀀스적용';
   COMMENT ON COLUMN "SCHEDULE"."CID" IS '시퀀스 적용';
   COMMENT ON COLUMN "SCHEDULE"."END_DATE" IS 'NULL이면 하루';
   COMMENT ON COLUMN "SCHEDULE"."STATUS" IS '삭제여부';
--------------------------------------------------------
--  DDL for Table SCHEDULE_TYPE
--------------------------------------------------------

  CREATE TABLE "SCHEDULE_TYPE" 
   (	"STID" NUMBER, 
	"ST_NAME" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCHEDULE_TYPE"."STID" IS '시퀀스 적용';
   COMMENT ON COLUMN "SCHEDULE_TYPE"."STATUS" IS '삭제여부';
--------------------------------------------------------
--  DDL for Table STUDY
--------------------------------------------------------

  CREATE TABLE "STUDY" 
   (	"SID" NUMBER, 
	"USER_NO" NUMBER, 
	"STD_NAME" VARCHAR2(20 BYTE), 
	"STD_LOCATION" VARCHAR2(10 BYTE), 
	"STD_LIMIT" NUMBER, 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'ING'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "STUDY"."SID" IS '시퀀스';
   COMMENT ON COLUMN "STUDY"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "STUDY"."STATUS" IS '진행중,마감,삭제';
REM INSERTING into APP_STUDY
SET DEFINE OFF;
REM INSERTING into APP_VACATION
SET DEFINE OFF;
REM INSERTING into CLASS
SET DEFINE OFF;
Insert into CLASS (CID,C_NAME,TID,PERSONNEL,STR_DATE,END_DATE,STATUS) values (1,'테스트1',1,30,to_date('19/10/12','RR/MM/DD'),to_date('19/10/12','RR/MM/DD'),'Y');
Insert into CLASS (CID,C_NAME,TID,PERSONNEL,STR_DATE,END_DATE,STATUS) values (2,'테스트2',2,30,to_date('19/10/12','RR/MM/DD'),to_date('19/10/12','RR/MM/DD'),'Y');
REM INSERTING into MEMBER
SET DEFINE OFF;
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (100001,1,'admin','dKScaY29PBLjawsodEfYM/dPOTf/Ey6/9wVLqhhiPDWnBbsYuC4qwDhLUSfblwFuY2CfcSvJDjUGz76pdZn0bw==','11','11','11','11','11',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (4,1,'1','Tf9Oo0DwqCPxXT9PAati6uDl2lecy4Ufjbnf6ExYsrN7iZA6dA4e4XLaeTpuedVg5ff5vQWKEqKAQz7W+kZRCg==','1','1','1','1','1',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (5,1,'2','QLJEESZB3XjdT5O2yRkN1G4AmRlNWkQle3761u+f9Gg9oe2gJERIyzQ6poj10+/XMU2v5YCsC8vxFa7Kno3BFA==','2','2','2','2','2',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (6,1,'3','O6+/CIgqLRATMJOhuEM/UFY7k8FKzQW3kCjrHRJ5kCckFFCYBlGZRQFCOmbCdq4mxDtzm8ZcThaxDDr2wgKuuw==','3','3','3','3','3',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (7,1,'4','oyHYtAXj7yYElZhHs20XHuvrxKiUHccKR4STWk/KXVgT3oTfoEnwZUmqYbIISMFjPOgbZ1KG6o+1PbJA2DHFaA==','4','4','4','4','4',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (8,1,'5','Bt8FNxmBojfQ7RFHL658lMmsDv8dBUE1FnENF7EKT7b0UXvaSmlfAtCnPdTbVDtGU98o9dCdq4b5L/ubhtAeJQ==','5','5','5','5','5',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (9,1,'6','PJrVUUenFE9gZzJ8O4LqcOfFQmrdnO6k0H3CkCI5v54Em4hiXrZdAUp3GPeTVGCMqwkheCxkPwIImD//o1guQA==','6','6','6','6','6',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (10,1,'7','8FIQxbQmPw7Ew5lb2rRY2B05U/NUqRCVIPFZ2x6IALzUW5fFbc6QofwnqwPguKmvhnN0cCPEBimTdBFtb5ZpgQ==','7','7','7','7','7',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (11,1,'8','vCO4sBdy0t1n77j+Gl5r0PRLl8NhAb5swJ8lO1PmjWeiLkZDBo39E0GYATTqV1cKz2XjBuTZbO9NVgOEiUyIpA==','8','8','8','8','8',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (12,1,'9','DcUm2MT6BAhPSypkM/TNFGZLk9+fuKngC3e6iQuDcE0klEyTyqaStRCFu0dvgYUsJ+eTYA8TeuOSkBjNTI8aRQ==','99',null,'9','9','9',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (13,1,'10','PBHk8xbJVqJ2VZAtwaGbkluIh9We/3ke6mPtyKBUVOxZTV6w9ArhUd+HrNbhAXYezFuw07gpvzqF9UMkk7IvNw==','10','10','10','10','10',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (14,1,'11','dKScaY29PBLjawsodEfYM/dPOTf/Ey6/9wVLqhhiPDWnBbsYuC4qwDhLUSfblwFuY2CfcSvJDjUGz76pdZn0bw==','11','11','11','11','11',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (15,1,'12','Wq20VSDc2HJrKCKnp4u1PXlPVXGZ1dSr3t0sVaS9bKc2B2BcVY3j24DI6GwxlkhFZhY+0TJ+gui2dX0ZMhE8uA==','12','12','12','12','12',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (16,1,'13','QT8rp4x+1MzvvgzE9R0+tcsV8T/smZ3kiEvpJQdnRmY6pdNEdqPfSocp/Y7qAd76Tz9m6Zv5Q/TYQ4LWS7v6ng==','13','13','1','3','13',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (17,1,'14','Xzp5m6IMIKIl911P4qyreZEt/NLyszO/Bis3rLtkYziMNEQw1boen9MY0+2CYwdOmZ4rLoEbxRxeLf6k4vMuWA==','14','14','14','14','14',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (18,1,'15','mmOYz/xVreNbOfHkHPRsfEkXRJYYU/+VcdCau1WniXb3LDTNeoeHZ076HCJuqiSU29ChMxacnk4jaafS0C3jGg==','15','15','15','15','15',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (19,1,'16','fHOUf6GCEjNCjdloTlLOkIEwqRuQPVF59zHJ3tYfBs7MpCenoaWqvvqjW+Wm3YTvwD8st3nzObB2ZIHquyQeDA==','1','61','6','16','16',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (20,1,'17','3C3mfrJI3NxQxjqr0byoM1rQEQbdj/cgWQB3wWH1WKe2HbPFazoymXWXo9uY/RkcPp5/31VarBUl8LU0LKxAiA==','17','17','17','17','17',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (21,1,'18','8Qe6LaBZ+mQOzLlTPoWaZDX2uDqi4GNqR0RN/c3jOm4fPMHJQ3vP1CZ1ryZaDQudZshsnmY0eqQVNCBHReQfuA==','18','18','18','18','18',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (22,1,'19','jYmqcB3lo1skz629IIiYauEzEdGnxjq+XHgMYryTmgV3w6eM9+5JUcGwn2hJB0whyh9wI+ib7mg8HbshNKmE0A==','19','19','19','19','19',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (23,1,'20','36XRzv0O/fX1K3ZRINpyxXBusd0RMjTP3zHjH5zQKDNm9qj3Iw8p6kLYOs/gJ0PcJQTNoHww9uhL+bHKNZZiZg==','20','20','20','20','02',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (24,1,'21','GY2r9LrCHPNc3bSNsPi2fFayvfY3ZyQq6nNC/mjAud+NN/PkehNGSOGfFkDhWPLlJ+Y22xIqkUMwfPMJ78uF2Q==','21','21','21','21','21',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (25,1,'22','atJ10mwgDoFTTZmWGDyHSN36vHsKARqQ9GMBYm1wmSNHRwPKyrD/i2fNhGtstVsjo5sD+9+1IY7sM3PPcBChZg==','22','22','22','22','22',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (26,1,'23','b/M04QUaCekBJ7pOMJ4Ca7gwFjos46NVryziMQ/25+mDDSAZajRyv8hjL9O2DLVhAqhPrnCrGjKUIFXrQAIiJQ==','23','23','23','2','323',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (27,1,'24','wAM7X1pIFaFymE1kA33UmoZj+4s6ceR/EezTMsjDgZxX4WMf30bWbG/w5YdjphUp/vz6KmZ14YbukB5UUv7dlA==','242','4','2424','2424','24',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (28,1,'25','XvYg/7LtRLQFMMCogP5rgJv3zJzp9YnrJRS/Qs7JSt5EkcYdqBZUSuvxBU2j2JT9+iGKm99zYly6oeoBJqR7cQ==','25','25','25','25','25',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (29,1,'26','4FOIbht5e8WoD5MjAvAgEmWlmdguJQLUGUHW5lJhTviPoFjgCQlNJmVfiAIA3xLCEA9pAlT9HluudddEF2PNMw==','26','26','26','26','26',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (30,1,'27','FPcFZkNc6kMJF2rWqK67aayPmeniEd9mInUitbs3x6UuH03kJUPku1NG284jpjbHI3pC5n/0iIvvzCFn98K0UQ==','27','272','27','27','27',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (31,1,'28','7b1IyDb4JrXtjWK0Ac0ZZ07xuGJ7nGikY5gZqFZPV0JsYyt8HT3uggnEjCOW2go6CNFgYX9ykaEYbKbZ3l2ycg==','28','28','28','28','28',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (32,1,'29','pkwOmZaWg+ciQTeycmNT/9Yw/BXM7aHHUWna72XJgCpU3+v/o5ApQwRP4yc8zOldDd//CP2644g1ennOiRz+OA==','29','29','29','29','29',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
Insert into MEMBER (USER_NO,CID,USER_ID,USER_PWD,USER_NAME,RRN,PHONE,EMAIL,ADDRESS,ENROLL_DATE,MODIFY_DATE,STATUS,"LEVEL",MAJOR,SMOKING,SEAT,EXP,CONSULT,APPROVE) values (33,1,'30','HMv/M+VWJ6UL7KjPXIn3fDFl3LMhgXEwhCPyUPC7C+lwC7/dktNd+i5XkRAmakAZTXB7UOfSe28JuB+7+AIxow==','303','030','303','030','30',to_date('19/10/16','RR/MM/DD'),to_date('19/10/16','RR/MM/DD'),'Y','3',null,'N',null,'N',null,'Y');
REM INSERTING into SCHEDULE
SET DEFINE OFF;
REM INSERTING into SCHEDULE_TYPE
SET DEFINE OFF;
Insert into SCHEDULE_TYPE (STID,ST_NAME,STATUS) values (0,'일정','Y');
Insert into SCHEDULE_TYPE (STID,ST_NAME,STATUS) values (1,'휴가','Y');
REM INSERTING into STUDY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PK_APP_STUDY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APP_STUDY" ON "APP_STUDY" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_APP_VACATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APP_VACATION" ON "APP_VACATION" ("VID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLASS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLASS" ON "CLASS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MEMBER" ON "MEMBER" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SCHEDULE" ON "SCHEDULE" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SCHEDULE_TYPE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SCHEDULE_TYPE" ON "SCHEDULE_TYPE" ("STID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_STUDY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_STUDY" ON "STUDY" ("SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table APP_STUDY
--------------------------------------------------------

  ALTER TABLE "APP_STUDY" ADD CONSTRAINT "PK_APP_STUDY" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APP_STUDY" MODIFY ("APP_DATE" NOT NULL ENABLE);
  ALTER TABLE "APP_STUDY" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "APP_STUDY" MODIFY ("SID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table APP_VACATION
--------------------------------------------------------

  ALTER TABLE "APP_VACATION" ADD CONSTRAINT "PK_APP_VACATION" PRIMARY KEY ("VID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APP_VACATION" MODIFY ("APPR_DATE" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("APP_DATE" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("APPR_YN" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("VID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "CLASS" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("C_NAME" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("PERSONNEL" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("STR_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MODIFY_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SCHEDULE
--------------------------------------------------------

  ALTER TABLE "SCHEDULE" ADD CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCHEDULE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE" MODIFY ("STR_DATE" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE" MODIFY ("SC_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE" MODIFY ("STID" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE" MODIFY ("SID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SCHEDULE_TYPE
--------------------------------------------------------

  ALTER TABLE "SCHEDULE_TYPE" ADD CONSTRAINT "PK_SCHEDULE_TYPE" PRIMARY KEY ("STID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SCHEDULE_TYPE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE_TYPE" MODIFY ("ST_NAME" NOT NULL ENABLE);
  ALTER TABLE "SCHEDULE_TYPE" MODIFY ("STID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table STUDY
--------------------------------------------------------

  ALTER TABLE "STUDY" ADD CONSTRAINT "PK_STUDY" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "STUDY" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "STUDY" MODIFY ("STD_LIMIT" NOT NULL ENABLE);
  ALTER TABLE "STUDY" MODIFY ("STD_LOCATION" NOT NULL ENABLE);
  ALTER TABLE "STUDY" MODIFY ("STD_NAME" NOT NULL ENABLE);
  ALTER TABLE "STUDY" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "STUDY" MODIFY ("SID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table APP_STUDY
--------------------------------------------------------

  ALTER TABLE "APP_STUDY" ADD CONSTRAINT "FK_STUDY_TO_APP_STUDY_1" FOREIGN KEY ("SID")
	  REFERENCES "STUDY" ("SID") ENABLE;



--- 호관 --- 

-- 공지사항 --
CREATE TABLE N_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 1,
    BCONTENT CLOB NOT NULL,
	BCOUNT	 NUMBER DEFAULT 0,
	BWRITER	 NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	 DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);

SELECT * FROM CLASS;
SELECT * FROM MEMBER;
SELECT * FROM N_BOARD;

INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '1번째 공지사항', DEFAULT, '1번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '2번째 공지사항', DEFAULT, '2번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '3번째 공지사항', DEFAULT, '3번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '4번째 공지사항', DEFAULT, '4번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '5번째 공지사항', DEFAULT, '5번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '6번째 공지사항', DEFAULT, '6번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '7번째 공지사항', DEFAULT, '7번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '8번째 공지사항', DEFAULT, '8번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '9번째 공지사항', DEFAULT, '9번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '10번째 공지사항', DEFAULT, '10번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '11번째 공지사항', DEFAULT, '11번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '12번째 공지사항', DEFAULT, '12번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '13번째 공지사항', DEFAULT, '13번째 공지사항 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '14번째 공지사항', DEFAULT, '14번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '15번째 공지사항', DEFAULT, '15번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '16번째 공지사항', DEFAULT, '16번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '17번째 공지사항', DEFAULT, '17번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '18번째 공지사항', DEFAULT, '18번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '19번째 공지사항', DEFAULT, '19번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '20번째 공지사항', DEFAULT, '20번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '21번째 공지사항', DEFAULT, '21번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO N_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '22번째 공지사항', DEFAULT, '22번째 공지사항 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);

SELECT * FROM N_BOARD;
-- 자유게시판 -- 

CREATE TABLE F_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 1,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);

INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '1번째 자유게시판', DEFAULT, '1번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '2번째 자유게시판', DEFAULT, '2번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '3번째 자유게시판', DEFAULT, '3번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '4번째 자유게시판', DEFAULT, '4번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '5번째 자유게시판', DEFAULT, '5번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '6번째 자유게시판', DEFAULT, '6번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '7번째 자유게시판', DEFAULT, '7번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '8번째 자유게시판', DEFAULT, '8번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '9번째 자유게시판', DEFAULT, '9번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '10번째 자유게시판', DEFAULT, '10번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '11번째 자유게시판', DEFAULT, '11번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '12번째 자유게시판', DEFAULT, '12번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '13번째 자유게시판', DEFAULT, '13번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '14번째 자유게시판', DEFAULT, '14번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '15번째 자유게시판', DEFAULT, '15번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '16번째 자유게시판', DEFAULT, '16번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '17번째 자유게시판', DEFAULT, '17번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '18번째 자유게시판', DEFAULT, '18번째 자유게시판 내용!', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '19번째 자유게시판', DEFAULT, '19번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '20번째 자유게시판', DEFAULT, '20번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '21번째 자유게시판', DEFAULT, '21번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);
INSERT INTO F_BOARD VALUES( SEQ_NBNO.NEXTVAL, 1, '22번째 자유게시판', DEFAULT, '22번째 자유게시판 내용', DEFAULT, 100001,SYSDATE,SYSDATE,DEFAULT);

CREATE TABLE N_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  FOREIGN KEY (BID) REFERENCES N_BOARD
);

CREATE TABLE F_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  FOREIGN KEY (BID) REFERENCES F_BOARD 
);



CREATE TABLE N_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES N_BOARD,
  FOREIGN KEY (RWRITER) REFERENCES MEMBER
);

CREATE TABLE F_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES F_BOARD(BID),
  FOREIGN KEY (RWRITER) REFERENCES MEMBER(USER_NO)
);


-- 준배-- 
CREATE TABLE T_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 2,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);

CREATE TABLE S_FILE(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 2,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);




CREATE TABLE T_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',

  FOREIGN KEY (BID) REFERENCES T_BOARD 
);

CREATE TABLE S_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',

  FOREIGN KEY (BID) REFERENCES S_FILE 
);


CREATE TABLE T_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES T_BOARD,
  FOREIGN KEY (RWRITER) REFERENCES MEMBER
);




-- 상재 --

CREATE TABLE TR(
    TRNO	NUMBER PRIMARY KEY NOT NULL,
    TR_NAME	VARCHAR2(100 BYTE) ,
    TR_MEMO	VARCHAR2(200 BYTE) ,
    TR_LATLNG	VARCHAR2(200 BYTE) NOT NULL,
    STATUS VARCHAR(1) NOT NULL,
    USER_NO NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
--채팅
CREATE TABLE CHATTING(
    USER_NO NUMBER NOT NULL,
   FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

--맛집별점
CREATE TABLE TR_SCORE(
    USER_NO NUMBER NOT NULL,
    TRNO NUMBER  NOT NULL,
    LIKE_SCORE NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (TRNO) REFERENCES TR(TRNO)
);

