/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-24 18:00:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.teacherPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import member.model.vo.Member;

public final class teacherCalendar_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ArrayList<Member> stdList = (ArrayList)session.getAttribute("stdList");


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src='lib/moment.min.js'></script>\r\n");
      out.write("<script src='js/fullcalendar.min.js'></script>\r\n");
      out.write("<script src='js/gcal.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- bPopup -->\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/bPopup/0.11.0/jquery.bpopup.min.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- locale = ko ==> 한글로 -->\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/locale/ko.js'></script>\r\n");
      out.write("\r\n");
      out.write("<!-- CSS 파일 -->\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.9.0/fullcalendar.min.css\" type='text/css' rel='stylesheet'/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar sDate;\r\n");
      out.write("\tvar eDate;\r\n");
      out.write("\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#calendar').fullCalendar({\r\n");
      out.write("\t\t\tnavLinkDayClick: function(){\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tselectable: true,\r\n");
      out.write("\t\t\tselect: function(startDate ,endDate){\r\n");
      out.write("\t\t\t\tconsole.log(startDate.format(), endDate.format());\r\n");
      out.write("\t\t\t\tsDate = startDate.format();\r\n");
      out.write("\t\t\t\teDate = endDate.format();\r\n");
      out.write("\t\t\t\tvar title = prompt(\"일정의 제목을 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\tsaveSchedule2(title, sDate, eDate);\r\n");
      out.write(" \t\t\t},\r\n");
      out.write("\t\t\tcustomButtons : {\r\n");
      out.write("\t\t\t\taddScheduleBtn : {\r\n");
      out.write("\t\t\t\t\ttext : '일정추가',\r\n");
      out.write("\t\t\t\t\tclick : function(event) {\r\n");
      out.write("/* \t\t\t\t\t\tif(sDate == null){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"날짜를 선택하세요.\");\r\n");
      out.write("\t\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t\t} */\r\n");
      out.write("\t\t\t\t\t\taddSchedule();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\theader : {\r\n");
      out.write("\t\t\t\tleft : 'prev,next',\r\n");
      out.write("\t\t\t\tcenter : 'title',\r\n");
      out.write("\t\t\t\tright : 'today,addScheduleBtn' \r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tdefaultDate : '2019-10-10',\r\n");
      out.write("\t\t\tnavLinks : true, // can click day/week names to navigate views\r\n");
      out.write("\t\t\teditable : false,\r\n");
      out.write("\t\t\teventLimit : true, // allow \"more\" link when too many events\r\n");
      out.write("\t\t\tevents : {\r\n");
      out.write("\t\t\t\turl: \"/KH_Groupware/showCalendar.te\",\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\terror:function(){\r\n");
      out.write("\t\t\t\t\talert(\"불러오기 실패\");\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teventDrop : function(event, delta, revertFunc){\r\n");
      out.write("\t\t\t\tif(!confirm(\"일정을 변경하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\t $(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t\t return false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\turl: \"/KH_Groupware/updateSchedule.te\",\r\n");
      out.write("\t\t\t\t\tdata: {scdNo:event.id, strDate:event.start.format(), endDate:event.end.format(), type:\"modify\"},\r\n");
      out.write("\t\t\t\t\tcache: false,\r\n");
      out.write("\t\t\t\t\tasync: false\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\t.done(function(data){\r\n");
      out.write("\t\t\t\t\tif(data > 0){\r\n");
      out.write("\t\t\t\t\t\talert(\"일정이 변경되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\teventClick : function(ev, jsEvent, view){\r\n");
      out.write("\t\t\t\tif(ev.type == \"V_W\"){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\turl: \"/KH_Groupware/showSchedule.te\",\r\n");
      out.write("\t\t\t\t\t\tdata: {stdNum: ev.userNum},\r\n");
      out.write("\t\t\t\t\t\tcache: false,\r\n");
      out.write("\t\t\t\t\t\tasync: false\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t.done(function(data){\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#stdList\").bPopup();\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tvar info = \"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<th>날짜</th>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\"<th>승인여부</th>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\tfor(key in data){\r\n");
      out.write("\t\t\t\t\t\t\tif(ev.id == data[key].id){\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: grey; color: white'>\"+data[key].start+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: grey; color: white'>\"+data[key].title+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"<td id = 'scdId' style = 'display: none;'>\"+data[key].id+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\tinfo += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\t\tif(data[key].type == \"V_N\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: red; color: white'>\"+data[key].start+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: red; color: white'>\"+data[key].title+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t\telse{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<tr>\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: blue; color: white'>\"+data[key].start+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"<td style = 'background: blue; color: white'>\"+data[key].title+\"</td>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t\tinfo += \"</tr>\";\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t$(\"#scdContents\").html(\r\n");
      out.write("\t\t\t\t\t\t\t\"\"+info\r\n");
      out.write("\t\t\t\t\t\t);\r\n");
      out.write("\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(ev.type == \"SCD\"){\r\n");
      out.write("\t\t\t\t\tif(!confirm(\"일정을 삭제하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\t\t return false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\t\t\turl: \"/KH_Groupware/updateSchedule.te\",\r\n");
      out.write("\t\t\t\t\t\tdata: {scdNo:ev.id, type:\"delete\"},\r\n");
      out.write("\t\t\t\t\t\tcache: false,\r\n");
      out.write("\t\t\t\t\t\tasync: false\r\n");
      out.write("\t\t\t\t\t})\r\n");
      out.write("\t\t\t\t\t.done(function(data){\r\n");
      out.write("\t\t\t\t\t\tif(data > 0){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"일정이 삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}); \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"td[class~='fc-past']\").off(\"click\");\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\tfunction addSchedule(){\r\n");
      out.write("\t\tvar scInfo = \"\";\r\n");
      out.write("\t\tscInfo += \"<div style='width:100%; height:30px;'><div style= 'width:30%; float:left; paddin-left:30px;'>일정내용</div><div style= 'width:60%; float:right;'><input id = 'scdName' type = 'text' value =''></div></div>\" \r\n");
      out.write("\t\tscInfo += \"<div style='width:100%; height:30px;'><div style= 'width:30%; float:left; paddin-left:30px;'>시작일</div><div style= 'width:60%; float:right;'><input id = 'strDate' type = 'date' style= 'width:150px;'  value =''></div></div>\"\r\n");
      out.write("\t\tscInfo += \"<div style='width:100%; height:30px;'><div style= 'width:30%; float:left; paddin-left:30px;''>마감일</div><div style= 'width:60%; float:right;'><input id = 'endDate' type = 'date' style= 'width:150px;'  value =''></div></div>\"\r\n");
      out.write("\t\tscInfo += \"<div style='width:100%; text-align:center; height:10px; margin-bottom:15px; margin-top:10px'><button onclick = 'saveSchedule();'>저장하기</</button></div> \"\r\n");
      out.write("\t\topenPop(\"일정 등록\", scInfo, 500);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openPop(subject, contents, widths){\r\n");
      out.write("\t\t$(\"#subject\").html(subject);\r\n");
      out.write("\t\t$(\"#contents\").html(contents);\r\n");
      out.write("\t\topenMsg(\"boxAlert\",widths);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction openMsg(baId, widths){\r\n");
      out.write("\t\t$(\"#\"+baId).css(\"width\",widths+\"px\");\r\n");
      out.write("\t\t$(\"#\"+baId).bPopup();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction closeMsg(baId){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#\"+baId).bPopup().close();\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction saveSchedule(){\r\n");
      out.write("\t\tvar scdName = $(\"#scdName\").val();\r\n");
      out.write("\t\tvar strDate = $(\"#strDate\").val();\r\n");
      out.write("\t\tvar endDate = $(\"#endDate\").val();\r\n");
      out.write("\t\tconsole.log(scdName);\r\n");
      out.write("\t\tconsole.log(strDate);\r\n");
      out.write("\t\tconsole.log(endDate);\r\n");
      out.write("\t\tif(!scdName){\r\n");
      out.write("\t\t\talert(\"일정 내용을 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!strDate){\r\n");
      out.write("\t\t\talert(\"시작일을 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif(!endDate){\r\n");
      out.write("\t\t\talert(\"마감일을 입력하세요.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/KH_Groupware/insertSchedule.te\",\r\n");
      out.write("\t\t\tcache:false,\r\n");
      out.write("\t\t\tasync:false,\r\n");
      out.write("\t\t\tdata:{scdName:scdName,\r\n");
      out.write("\t\t\t\t  strDate:strDate,\r\n");
      out.write("\t\t\t\t  endDate:endDate\t\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess:function(data){\t\r\n");
      out.write(" \t\t\t\tif(data>0){\r\n");
      out.write("\t\t\t\t\tcloseMsg(\"boxAlert\");\r\n");
      out.write("\t\t\t\t\talert(\"정상으로 저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"addEventSource\",data);\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction saveSchedule2(title, sDate, eDate){\r\n");
      out.write("\t\t\tvar scdName = title;\r\n");
      out.write("\t\t\tvar strDate = sDate;\r\n");
      out.write("\t\t\tvar endDate = eDate;\r\n");
      out.write("\t\t\tconsole.log(scdName);\r\n");
      out.write("\t\t\tconsole.log(strDate);\r\n");
      out.write("\t\t\tconsole.log(endDate);\r\n");
      out.write("\t\t\tif(!scdName){\r\n");
      out.write("\t\t\t\talert(\"일정 내용을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!strDate){\r\n");
      out.write("\t\t\t\talert(\"시작일을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(!endDate){\r\n");
      out.write("\t\t\t\talert(\"마감일을 입력하세요.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\t\turl:\"/KH_Groupware/insertSchedule.te\",\r\n");
      out.write("\t\t\t\tcache:false,\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tdata:{scdName:scdName,\r\n");
      out.write("\t\t\t\t\t  strDate:strDate,\r\n");
      out.write("\t\t\t\t\t  endDate:endDate\t\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tsuccess:function(data){\t\r\n");
      out.write("\t \t\t\t\tif(data>0){\r\n");
      out.write("\t\t\t\t\t\tcloseMsg(\"boxAlert\");\r\n");
      out.write("\t\t\t\t\t\talert(\"정상으로 저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#calendar\").fullCalendar(\"addEventSource\",data);\r\n");
      out.write("\t\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t\t} \r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>강사일정관리</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t#outer{\r\n");
      out.write("\t\tmargin: 5%;\r\n");
      out.write("\t\tmargin-top: 3%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \t#stdList{\r\n");
      out.write(" \t\tbackground: whitesmoke;\r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tmargin: 2%;\r\n");
      out.write("\t\twidth: 20%;\r\n");
      out.write("\t\theight: 330px;\r\n");
      out.write("\t\tpadding: 2%;\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("\t#stdListTable{\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#calendar {\r\n");
      out.write("\t\tmax-width: 50%;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tmargin: 2%;\r\n");
      out.write("\t\tmargin-left : 20%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tpadding: 2%;\r\n");
      out.write("\t\theight: 600px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#scdContentsDiv{\r\n");
      out.write("\t\theight: 250px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#scdContents{\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tborder-collapse: collapse;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#scdContents td{\r\n");
      out.write("\t\tborder-bottom: 1px solid grey;\r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t\theight: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#scdContents th{\r\n");
      out.write("\t\tborder-bottom: 1px solid grey;\r\n");
      out.write("\t\twidth: 300px;\r\n");
      out.write("\t\theight: 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t.buttons{\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#appBtn{\r\n");
      out.write("\t\tbackground: black; \r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rejBtn{\r\n");
      out.write("\t\tbackground: white; \r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#appBtn:hover{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground: grey;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#rejBtn:hover{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t\tbackground: grey;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.buttons button{\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write(" \t.fc-past{ background:whitesmoke}\r\n");
      out.write(" \t\t\r\n");
      out.write(" \t\r\n");
      out.write("\t.fc-sun { color:red; }\r\n");
      out.write("\t.fc-sat { color:blue;  }\r\n");
      out.write("\t.fc-day:hover{background: whitesmoke; cursor: pointer;}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<header>\t\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id = \"outer\">\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"calendar\"></div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id = \"stdList\">\r\n");
      out.write("\t\t<div id = \"stdListTable\">\r\n");
      out.write("\t\t\t<div id = \"scdContentsDiv\">\r\n");
      out.write("\t\t\t<table id = \"scdContents\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class = \"buttons\" align=\"center\">\r\n");
      out.write("\t\t\t\t<button id = \"appBtn\" style = \" border: none;\" onclick = \"appVac();\">휴가승인</button>\r\n");
      out.write("\t\t\t\t<button id = \"rejBtn\" style = \" border: 1px soild black;\" onclick = \"recVac();\">휴가불승인</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class = \"box\" style = \"width:500px; display:none; background:white;\" id =\"boxAlert\">\r\n");
      out.write("\t<div class = \"boxHead\" style = \"background:white; paddin-left:15px\">\r\n");
      out.write("\t\t<h3 class =\"boxTitle\" id = \"subject\" style = \"background:white\"></h3>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class = \"boxBody\" id = \"contents\" style = \"font-size:15px; background:white;\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction appVac(){\r\n");
      out.write("\t\tif(!confirm(\"휴가를 승인하시겠습니까?\")){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/KH_Groupware/approveVac.te\",\r\n");
      out.write("\t\t\tcache:false,\r\n");
      out.write("\t\t\tasync:false,\r\n");
      out.write("\t\t\tdata:{scdId:$(\"#scdId\").text(),\r\n");
      out.write("\t\t\t\ttype:\"approve\"},\r\n");
      out.write("\t\t\tsuccess:function(data){\t\r\n");
      out.write(" \t\t\t\tif(data>0){\r\n");
      out.write("\t\t\t\t\talert(\"정상으로 저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#stdList\").bPopup().close();\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"addEventSource\",data);\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction recVac(){\r\n");
      out.write("\t\tif(!confirm(\"휴가를 거절하시겠습니까?\")){\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype:\"post\",\r\n");
      out.write("\t\t\turl:\"/KH_Groupware/approveVac.te\",\r\n");
      out.write("\t\t\tcache:false,\r\n");
      out.write("\t\t\tasync:false,\r\n");
      out.write("\t\t\tdata:{scdId:$(\"#scdId\").text(),\r\n");
      out.write("\t\t\t\ttype:\"reject\"},\r\n");
      out.write("\t\t\tsuccess:function(data){\t\r\n");
      out.write(" \t\t\t\tif(data>0){\r\n");
      out.write("\t\t\t\t\talert(\"정상으로 저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#stdList\").bPopup().close();\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"addEventSource\",data);\r\n");
      out.write("\t\t\t\t\t$(\"#calendar\").fullCalendar(\"refetchEvents\");\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
