-- LAST - 

DROP TABLE TR_SCORE;
DROP TABLE SEAT;
DROP TABLE STUDY;
DROP TABLE F_BOARD;
DROP TABLE N_BOARD;
DROP  TABLE T_BOARD;
DROP  TABLE T_REPLY;
DROP  TABLE N_REPLY;
DROP  TABLE F_REPLY;
DROP TABLE N_ATTACH; 
DROP TABLE F_ATTACH;
DROP TABLE T_ATTACH;
DROP TABLE S_ATTACH;
DROP TABLE  SEAT;
DROP TABLE CHATTING; 
DROP TABLE TR_SCORE;
DROP TABLE TR;


-- 시퀀스  -- 

DROP SEQUENCE SEQ_NBNO; 
DROP SEQUENCE SEQ_FBNO;
DROP SEQUENCE SEQ_TBNO;
DROP SEQUENCE SEQ_SCHEDULE;
DROP SEQUENCE SEQ_NAFID; 
DROP SEQUENCE SEQ_FAFID; 
DROP SEQUENCE SEQ_TAFID; 
DROP SEQUENCE SEQ_SAFID; 
DROP SEQUENCE SEQ_NRID;
DROP SEQUENCE SEQ_FRID;
DROP SEQUENCE SEQ_TRID;
DROP SEQUENCE SEQ_TRNO;
DROP SEQUENCE SEQ_SBNO;
DROP SEQUENCE SEQ_APP_STUDY;




CREATE SEQUENCE SEQ_NBNO;
--공지사항 시퀀스 
CREATE SEQUENCE SEQ_FBNO; 
--자유게시판 시퀀스 
CREATE SEQUENCE SEQ_TBNO; 
--사진게시판 시퀀스 

CREATE SEQUENCE  "SEQ_SCHEDULE"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
-- 스케줄 시퀀스 
CREATE SEQUENCE  "SEQ_STUDY"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;   
-- 스터디시퀀스 
CREATE SEQUENCE  "SEQ_APP_STUDY"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
-- 스터디 참가시퀀스
CREATE SEQUENCE  "SEQ_UNO"  MINVALUE 1 MAXVALUE 10000 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ; 	    
-- 유저시퀀스
CREATE SEQUENCE  "SEQ_VACATION"  MINVALUE 1 MAXVALUE 100000 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;   
--휴가시퀀스

CREATE SEQUENCE SEQ_NAFID;
-- 공지사항 첨부파일 시퀀스
CREATE SEQUENCE SEQ_FAFID; 
-- 자유게시판 첨부파일 시퀀스
CREATE SEQUENCE SEQ_TAFID; 
-- 사진게시판 첨부파일 시퀀스 
CREATE SEQUENCE SEQ_SAFID;
-- 공유자료 첨부파일 시퀀스 

CREATE SEQUENCE SEQ_SBNO;
-- 자료실 시퀀스 

CREATE SEQUENCE SEQ_NRID; 
-- 공지사항 리플 시퀀스 
CREATE SEQUENCE SEQ_FRID;  
-- 자유게시판 리플 시퀀스 	
CREATE SEQUENCE SEQ_TRID; 
-- 사진게시판 리플 시퀀스 
Create sequence SEQ_TRNO minvalue 1 maxvalue 10000 start with 1 increment by 1;
-- 맛집 시퀀스


-- 강현모 --


--------------------------------------------------------
--  DDL for Table CLASS
--------------------------------------------------------

  CREATE TABLE "CLASS" 
   (	"CID" NUMBER, 
	"C_NAME" VARCHAR2(40 BYTE), 
	"TID" NUMBER, 
	"PERSONNEL" NUMBER, 
	"STR_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS" VARCHAR2(3 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

     CREATE TABLE "MEMBER" 
   (	"USER_NO" NUMBER, 
	"CID" NUMBER, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"USER_PWD" VARCHAR2(100 BYTE), 
	"USER_NAME" VARCHAR2(15 BYTE), 
	"RRN" VARCHAR2(50 BYTE), 
	"PHONE" VARCHAR2(13 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(100 BYTE), 
	"ENROLL_DATE" DATE, 
	"MODIFY_DATE" DATE, 
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"LEVEL" VARCHAR2(1 BYTE) DEFAULT null, 
	"MAJOR" VARCHAR2(3 BYTE) DEFAULT null, 
	"SMOKING" VARCHAR2(1 BYTE) DEFAULT null, 
	"SEAT" VARCHAR2(3 BYTE) DEFAULT 'N', 
	"EXP" VARCHAR2(1 BYTE) DEFAULT null, 
	"CONSULT" VARCHAR2(200 BYTE) DEFAULT null, 
	"APPROVE" VARCHAR2(3 BYTE) DEFAULT 'N'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "MEMBER"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."CID" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴여부';

   COMMENT ON COLUMN "MEMBER"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."CID" IS '시퀀스 적용';
   COMMENT ON COLUMN "MEMBER"."STATUS" IS '탈퇴여부';
--------------------------------------------------------
--  DDL for Table SCHEDULE
--------------------------------------------------------

  CREATE TABLE "SCHEDULE" 
   (	"SID" NUMBER NOT NULL ENABLE, 
	"CID" NUMBER NOT NULL ENABLE, 
	"STID" NUMBER NOT NULL ENABLE, 
	"SC_NAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"STR_DATE" DATE NOT NULL ENABLE, 
	"END_DATE" DATE, 
    "SC_TYPE" VARCHAR2(3 BYTE)  NOT NULL ENABLE,
	"STATUS" VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE, 
	 CONSTRAINT "PK_SCHEDULE" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SCHEDULE"."SID" IS '시퀀스적용';
   COMMENT ON COLUMN "SCHEDULE"."CID" IS '시퀀스 적용';
   COMMENT ON COLUMN "SCHEDULE"."END_DATE" IS 'NULL이면 하루';
   COMMENT ON COLUMN "SCHEDULE"."STATUS" IS '삭제여부';
   
   --------------------------------------------------------
--  DDL for Table APP_VACATION
--------------------------------------------------------

  CREATE TABLE "APP_VACATION" 
   (	"VID" NUMBER, 
	"USER_NO" NUMBER, 
	"SID" NUMBER, 
	"APPR_YN" VARCHAR2(1 BYTE), 
	"APP_DATE" DATE DEFAULT SYSDATE, 
	"APPR_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APP_VACATION"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "APP_VACATION"."SID" IS '시퀀스적용';

--------------------------------------------------------
--  DDL for Table STUDY
--------------------------------------------------------

  CREATE TABLE "STUDY" 
   (	"STID" NUMBER NOT NULL ENABLE, 
	"USER_NO" NUMBER NOT NULL ENABLE, 
	"ST_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ST_LOCATION" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"ST_TIME" VARCHAR2(30 BYTE) NOT NULL ENABLE,
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"STATUS" VARCHAR2(10 BYTE) DEFAULT 'ING' NOT NULL ENABLE, 
	 CONSTRAINT "PK_STUDY" PRIMARY KEY ("STID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "STUDY"."STID" IS '시퀀스';
   COMMENT ON COLUMN "STUDY"."USER_NO" IS '시퀀스 적용';
   COMMENT ON COLUMN "STUDY"."STATUS" IS '진행중,마감,삭제';
REM INSERTING into APP_STUDY
SET DEFINE OFF;
REM INSERTING into APP_VACATION
SET DEFINE OFF;
REM INSERTING into CLASS
SET DEFINE OFF;
REM INSERTING into MEMBER
SET DEFINE OFF;
REM INSERTING into SCHEDULE
SET DEFINE OFF;
REM INSERTING into STUDY
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Table APP_STUDY
--------------------------------------------------------

  CREATE TABLE "APP_STUDY" 
   (	"ASID" NUMBER NOT NULL ENABLE,
	"STID" NUMBER NOT NULL ENABLE, 
	"USER_NO" NUMBER NOT NULL ENABLE, 
	"APP_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	 CONSTRAINT "PK_APP_STUDY" PRIMARY KEY ("ASID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_STUDY_TO_APP_STUDY_1" FOREIGN KEY ("STID")
	  REFERENCES "STUDY" ("STID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "APP_STUDY"."STID" IS '시퀀스';
   COMMENT ON COLUMN "APP_STUDY"."USER_NO" IS '시퀀스 적용';

   COMMENT ON COLUMN "APP_STUDY"."STID" IS '시퀀스';
   COMMENT ON COLUMN "APP_STUDY"."USER_NO" IS '시퀀스 적용';

--------------------------------------------------------
--  DDL for Index PK_APP_VACATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_APP_VACATION" ON "APP_VACATION" ("VID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CLASS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_CLASS" ON "CLASS" ("CID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MEMBER
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_MEMBER" ON "MEMBER" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;


--------------------------------------------------------
--  Constraints for Table APP_VACATION
--------------------------------------------------------

  ALTER TABLE "APP_VACATION" ADD CONSTRAINT "PK_APP_VACATION" PRIMARY KEY ("VID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "APP_VACATION" MODIFY ("APPR_DATE" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("APPR_YN" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("SID" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "APP_VACATION" MODIFY ("VID" NOT NULL ENABLE);
  
  
--------------------------------------------------------
--  Constraints for Table CLASS
--------------------------------------------------------

  ALTER TABLE "CLASS" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("C_NAME" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("TID" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("PERSONNEL" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("STR_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "CLASS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "CLASS" ADD CONSTRAINT "PK_CLASS" PRIMARY KEY ("CID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("USER_NO" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("CID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_PWD" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("ENROLL_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("MODIFY_DATE" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;

---------------------------------------------------------
-- 첫 세팅
---------------------------------------------------------

Insert into CLASS values (1,'자바 1반',100001,30,to_date('19/6/12','RR/MM/DD'),to_date('19/12/12','RR/MM/DD'),'Y');
Insert into class values (2,'자바 2반',2,30,to_date('19/1/12','RR/MM/DD'),to_date('19/5/12','RR/MM/DD'),'Y');




--- 호관 --- 

-- 공지사항 --
CREATE TABLE N_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 1,
    BCONTENT CLOB NOT NULL,
	BCOUNT	 NUMBER DEFAULT 0,
	BWRITER	 NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	 DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);

SELECT * FROM CLASS;
SELECT * FROM MEMBER;
SELECT * FROM N_BOARD;



SELECT * FROM N_BOARD;
-- 자유게시판 -- 

CREATE TABLE F_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 1,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);


CREATE TABLE N_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  FOREIGN KEY (BID) REFERENCES N_BOARD
);

CREATE TABLE F_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',
  FOREIGN KEY (BID) REFERENCES F_BOARD 
);



CREATE TABLE N_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES N_BOARD,
  FOREIGN KEY (RWRITER) REFERENCES MEMBER
);

CREATE TABLE F_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES F_BOARD(BID),
  FOREIGN KEY (RWRITER) REFERENCES MEMBER(USER_NO)
);


-- 준배-- 
CREATE TABLE T_BOARD(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 2,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);

CREATE TABLE S_FILE(
	BID	NUMBER PRIMARY KEY,
	CID	NUMBER NOT NULL REFERENCES CLASS(CID),
    BTITLE VARCHAR2(100) NOT NULL,
	BTYPE VARCHAR2(1) DEFAULT 2,
    BCONTENT CLOB NOT NULL,
	BCOUNT	NUMBER DEFAULT 0,
	BWRITER	NUMBER NOT NULL REFERENCES MEMBER(USER_NO),
	CREATE_DATE	DATE DEFAULT SYSDATE,
	MODIFY_DATE	DATE DEFAULT SYSDATE,
	STATUS	VARCHAR2(1) DEFAULT 'Y'
);




CREATE TABLE T_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',

  FOREIGN KEY (BID) REFERENCES T_BOARD 
);

CREATE TABLE S_ATTACH(
  FID NUMBER PRIMARY KEY,
  BID NUMBER NOT NULL,
  ORIGIN_NAME VARCHAR2(255) NOT NULL,
  CHANGE_NAME VARCHAR2(255) NOT NULL,
  FILE_PATH VARCHAR2(1000) NOT NULL,
  UPLOAD_DATE DATE DEFAULT SYSDATE,
  FILE_LEVEL NUMBER,
  DOWNLOAD_COUNT NUMBER DEFAULT 0,
  STATUS VARCHAR2(1) DEFAULT 'Y',

  FOREIGN KEY (BID) REFERENCES S_FILE 
);


CREATE TABLE T_REPLY(
  RID NUMBER PRIMARY KEY,
  RCONTENT VARCHAR2(400),
  REF_BID NUMBER,
  RWRITER NUMBER,
  CREATE_DATE DATE,
  MODIFY_DATE DATE,
  RECOMMAND NUMBER DEFAULT 0,
  DUPLICATION VARCHAR2(1000),
  STATUS VARCHAR2(1) DEFAULT 'Y' CHECK (STATUS IN ('Y', 'N')),
  FOREIGN KEY (REF_BID) REFERENCES T_BOARD,
  FOREIGN KEY (RWRITER) REFERENCES MEMBER
);




-- 상재 --

CREATE TABLE TR(
    TRNO	NUMBER PRIMARY KEY NOT NULL,
    TR_NAME	VARCHAR2(100 BYTE) ,
    TR_MEMO	VARCHAR2(200 BYTE) ,
    TR_LATLNG	VARCHAR2(200 BYTE) NOT NULL,
    STATUS VARCHAR(1) NOT NULL,
    USER_NO NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);
--채팅
CREATE TABLE CHATTING(
    USER_NO NUMBER NOT NULL,
   FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

--맛집별점
CREATE TABLE TR_SCORE(
    USER_NO NUMBER NOT NULL,
    TRNO NUMBER  NOT NULL,
    LIKE_SCORE NUMBER NOT NULL,
    FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    FOREIGN KEY (TRNO) REFERENCES TR(TRNO)
);

