/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-26 03:26:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.studentPage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class study_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 
	Member loginuser =  (Member)session.getAttribute("loginUser");
	int stcount = 1;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/bPopup/0.11.0/jquery.bpopup.min.js'></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://unpkg.com/flickity@2/dist/flickity.min.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("#outer{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mySlide div[choose=\"study\"]{\r\n");
      out.write("  width: 37%;\r\n");
      out.write("  height: 150px;\r\n");
      out.write("\tmargin-left:31.5%;\r\n");
      out.write("  margin-right:31.5%;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transform-style: preserve-3d;\r\n");
      out.write("  transform-origin: center right;\r\n");
      out.write("  transition: transform 1s;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#allSlide div[choose=\"study\"]{\r\n");
      out.write("  width: 70%;\r\n");
      out.write("  height: 150px;\r\n");
      out.write("  margin-left:15%;\r\n");
      out.write("  margin-right:15%;\r\n");
      out.write("  cursor: pointer;\r\n");
      out.write("  transform-style: preserve-3d;\r\n");
      out.write("  transform-origin: center right;\r\n");
      out.write("  transition: transform 1s;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".front {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  color: #262A2D;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  backface-visibility: hidden;\r\n");
      out.write("  background: #F6F6F6;\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".back {\r\n");
      out.write("  position: absolute;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("  height: 100%;\r\n");
      out.write("  color: #262A2D;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  backface-visibility: hidden;\r\n");
      out.write("  background: #F6F6F6;\r\n");
      out.write("  transform: rotateX(180deg);\r\n");
      out.write("  padding: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".main-carousel{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin: auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mySlide .carousel-cell{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#allSlide .carousel-cell{\r\n");
      out.write("\twidth: 33%;\r\n");
      out.write("\tpadding: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".is-selected div[choose=\"study\"]{\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\tborder: 5px solid  #E7E3E3;\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#studyInfo{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder: 2px solid 262A2D;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#attendance{\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tborder-collapse: collapse;\r\n");
      out.write("\tborder: 2px solid 262A2D;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#outer th{\r\n");
      out.write("\tcolor:#262A2D;\r\n");
      out.write("\tbackground: #E7E3E3;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#outer td{\r\n");
      out.write("\tcolor:#262A2D;\r\n");
      out.write("\tborder-bottom: 2px solid lightgrey;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#openForm{\r\n");
      out.write("\tbackground:  #F6F6F6;\r\n");
      out.write("\twidth: 400px;\r\n");
      out.write("\theight: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input{\r\n");
      out.write("\tmargin-left: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#openForm td{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"outer\">\r\n");
      out.write("\t\t<div id=\"mySlide\">\r\n");
      out.write("\t\t\t<h2 style = \"text-align: center; margin-bottom: 35px; color:#262A2D; \">내 스터디</h2>\r\n");
      out.write("\t\t\t<div id = \"myStudy\" class=\"main-carousel\" style=\"width: 50%;\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"allSlide\" style = \"margin-top: 100px;\">\r\n");
      out.write("\t\t<h2 style = \"text-align: center; margin-bottom: 0px; color:#262A2D;\">모든 스터디</h2>\r\n");
      out.write("\t\t<div style = \"height: 30px; width: 6.85%; margin-left: 80%; margin-bottom: 5px;\">\r\n");
      out.write("\t\t\t<button id = \"openStBtn\" onclick = \"openStudy();\" style = \"width: 100%; height: 100%; background: #262A2D; color: #F6F6F6\">스터디 개설</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id = \"allStudy\" class=\"main-carousel\">\r\n");
      out.write("\t\t\t<div class=\"carousel-cell\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"study0\" class=\"change\" choose=\"study\"\r\n");
      out.write("\t\t\t\t\t\t\tonclick=\"toggleTrsf(0);\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"front\" style = \"margin: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id = \"studyInfo\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th colspan=\"2\">sdfsfsfsfsdfsfsds</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td style = \"width: 30%;\">스터디장</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>dfsssfsf</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>장소</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>시간</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>dd</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"back\" style = \"margin: auto;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<table id = \"attendance\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style = \"width: 30%; text-align: left; padding-left: 10px;\">참여인원</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<th style = \"text-align: right; padding-right: 20px;\">5/5</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>강현모</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td>ㄴㅇㄹㄴㅇㄹㄴㅇ</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<div id = \"openForm\" style=\"display: none;\">\r\n");
      out.write("\t\t<table id = \"openFormTable\" style = \"margin: auto; margin-top: 2%;\">\r\n");
      out.write("\t\t\t<h2 style = \"text-align: center; margin-bottom: 20px; color:#262A2D; \">스터디 개설</h2>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>제목</td>\r\n");
      out.write("\t\t\t\t<td><input type = \"text\" id = \"title\" maxlength=\"15\" required=\"required\" placeholder=\"주제와 간단한 소개\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>장소</td>\r\n");
      out.write("\t\t\t\t<td><input type = \"text\" id = \"location\" maxlength=\"15\" required=\"required\" placeholder=\"ex)학원앞 까페\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td>시간</td>\r\n");
      out.write("\t\t\t\t<td><input type = \"text\" id = \"time\" maxlength=\"15\" required=\"required\" placeholder=\"ex)매주 수요일 13시\"></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\"><button id = \"openBtn\" style = \"width: 33%; margin-left: 33%; margin-right: 33%; margin-top: 20px;  background: #262A2D; color: #F6F6F6\">개설하기</button></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://unpkg.com/flickity@2/dist/flickity.pkgd.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction toggleTrsf(id) {\r\n");
      out.write("\t\t\tvar card = $(\"#study\" + id);\r\n");
      out.write("\t\t\tif (card.hasClass(\"change\") == true) {\r\n");
      out.write("\t\t\t\tcard.css(\"transform\", \"rotateX(-180deg)\");\r\n");
      out.write("\t\t\t\tcard.removeClass(\"change\");\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\tcard.css(\"transform\", \"\");\r\n");
      out.write("\t\t\t\tcard.addClass(\"change\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $myStudy = $('#myStudy').flickity({\r\n");
      out.write("\t\t\t  // options\r\n");
      out.write("\t\t\t  cellAlign: 'center',\r\n");
      out.write("\t\t\t  contain: false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar $allStudy = $('#allStudy').flickity({\r\n");
      out.write("\t\t\t  // options\r\n");
      out.write("\t\t\t  cellAlign: 'center',\r\n");
      out.write("\t\t\t  contain: false\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction openStudy(){\r\n");
      out.write("\t\t\t$(\"#openForm\").bPopup();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar stcount = 1;\r\n");
      out.write("\t\tvar studyList;\r\n");
      out.write("\t\tvar appStudyList;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\t url:\"/KH_Groupware/showStudy.st\",\r\n");
      out.write("\t         data:{cid : ");
      out.print(loginuser.getcId());
      out.write("\r\n");
      out.write("\t         }, \r\n");
      out.write("\t         success:function(data){   \r\n");
      out.write("\t        \t \r\n");
      out.write("\t        \t studyList = data;\r\n");
      out.write("\t        \t $.ajax({\r\n");
      out.write("\t    \t\t\t url:\"/KH_Groupware/showAppStudy.st\",\r\n");
      out.write("\t    \t         data:{cid : ");
      out.print(loginuser.getcId());
      out.write("\r\n");
      out.write("\t    \t         }, \r\n");
      out.write("\t    \t         success:function(data){   \r\n");
      out.write("\t    \t        \t \r\n");
      out.write("\t    \t        \t appStudyList = data;\r\n");
      out.write("\t    \t        \t\r\n");
      out.write("\t    \t            }\r\n");
      out.write("\t    \t         });  \r\n");
      out.write("\t        \t \r\n");
      out.write("\t        \t for(var i in studyList){\r\n");
      out.write("\t\t        \tvar title = studyList[i].stName;\r\n");
      out.write("\t\t        \tvar location = studyList[i].location;\r\n");
      out.write("\t\t        \tvar time = studyList[i].time;\r\n");
      out.write("\t\t        \tvar openDate = studyList[i].openDate;\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tvar $study = $(makeMyStudy(stcount, title, location, time, openDate));\r\n");
      out.write("\t\t\t\t\t\t\t        \r\n");
      out.write("\t\t        \tstcount++;\r\n");
      out.write("\t\t        \t\r\n");
      out.write("\t\t        \tif(");
      out.print(loginuser.getUserNo());
      out.write("==data[i].userNo){\r\n");
      out.write("\t        \t  \t\t$myStudy.flickity('append', $study);\r\n");
      out.write("\t\t        \t}else{\r\n");
      out.write("\t        \t  \t\t$allStudy.flickity('append', $study);\t\r\n");
      out.write("\t\t        \t\t}\r\n");
      out.write("\t\t        \t}\r\n");
      out.write("\t            }\r\n");
      out.write("\t         });  \r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"#openBtn\").click(function(){\r\n");
      out.write("\t\t\tif(!confirm(\"정말로 스터디를 개설하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t$(\"#title\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#location\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#time\").val(\"\");\r\n");
      out.write("\t\t\t\t$(\"#openForm\").bPopup().close();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t         url:\"/KH_Groupware/openStduy.st\",\r\n");
      out.write("\t\t         data:{userNo : ");
      out.print(loginuser.getUserNo());
      out.write(",\r\n");
      out.write("\t\t        \t title : $(\"#title\").val(),\r\n");
      out.write("\t\t        \t location : $(\"#location\").val(),\r\n");
      out.write("\t\t        \t time : $(\"#time\").val(),\r\n");
      out.write("\t\t        \t date : date_to_str(new Date())\r\n");
      out.write("\t\t         }, \r\n");
      out.write("\t\t         success:function(data){   \r\n");
      out.write("\t\t        \tvar title = data.stName;\r\n");
      out.write("\t\t        \tvar location = data.location;\r\n");
      out.write("\t\t        \tvar time = data.time;\r\n");
      out.write("\t\t        \tvar openDate = data.openDate;\r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t        \t \r\n");
      out.write("\t\t        \t var $study = $(makeMyStudy(");
      out.print(stcount);
      out.write(", title, location, time, openDate));\r\n");
      out.write("\t\t        \t  $myStudy.flickity('append', $study);\r\n");
      out.write("\t\t            alert(\"저장이 완료되었습니다.\"); \r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t         });  \r\n");
      out.write("\t\t\t$(\"#title\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#location\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#time\").val(\"\");\r\n");
      out.write("\t\t\t$(\"#openForm\").bPopup().close();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction date_to_str(format)\r\n");
      out.write("\r\n");
      out.write("\t\t{\r\n");
      out.write("\r\n");
      out.write("\t\t    var year = format.getFullYear();\r\n");
      out.write("\r\n");
      out.write("\t\t    var month = format.getMonth() + 1;\r\n");
      out.write("\r\n");
      out.write("\t\t    if(month<10) month = '0' + month;\r\n");
      out.write("\r\n");
      out.write("\t\t    var date = format.getDate();\r\n");
      out.write("\r\n");
      out.write("\t\t    if(date<10) date = '0' + date;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t    return year + \"-\" + month + \"-\" + date;\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction makeMyStudy(stNo, title, location, time, openDate){\r\n");
      out.write("\t\t\tvar count = 1;\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn \"<div class='carousel-cell'>\"+\t\r\n");
      out.write("\t\t\t\"<div>\"+\r\n");
      out.write("\t\t\t\t\"<div id='study\"+stNo+\"' class='change' choose='study'\"+\r\n");
      out.write("\t\t\t\t\t\"onclick='toggleTrsf(\"+stNo+\");'>\"+\r\n");
      out.write("\t\t\t\t\t\"<div class='front' style = 'margin: auto;'>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<table id = 'studyInfo'>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th class = 'frontTh' colspan='2'>\"+title+\"</th>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td style = 'width: 30%;'>스터디장</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>");
      out.print(loginuser.getUserName());
      out.write("</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>장소</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>\"+location+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>시간</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>\"+time+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>\"+openDate+\"</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td class = 'btnTd'><button id = 'appBtn' onclick = 'appStudy(\"+stcount+\");' style = 'width:40%; height:80%; margin-left:50%; background:#262A2D; color:#F6F6F6'>신청하기</button></td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\"</table>\"+\r\n");
      out.write("\t\t\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\t\t\t\"<div class='back' style = 'margin: auto;'>\"+\r\n");
      out.write("\t\t\t\t\t\t\"<table id = 'attendance'>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th class = 'backTh' style = 'width: 30%; text-align: left; padding-left: 10px;'>참여인원</th>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<th class = 'backTh' style = 'text-align: right; padding-right: 20px;'>\"+count+\"/5</th>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>");
      out.print(loginuser.getUserName());
      out.write("</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\t\"<td>");
      out.print(loginuser.getPhone());
      out.write("</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"</tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\"</table>\"+\r\n");
      out.write("\t\t\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\t\"</div>\"+\r\n");
      out.write("\t\t\"</div>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction appStudy(stNo){\r\n");
      out.write("\t\t\tif(!confirm(\"스터디에 참여하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t return false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t         url:\"/KH_Groupware/appStudy.st\",\r\n");
      out.write("\t\t         data:{userNo : ");
      out.print(loginuser.getUserNo());
      out.write(",\r\n");
      out.write("\t\t        \t stNo : stNo\r\n");
      out.write("\t\t         }, \r\n");
      out.write("\t\t         success:function(data){   \r\n");
      out.write("\t\t        \t alert(\"ddd\");\r\n");
      out.write("\t\t        \t$(\"#study\"+stNo+\" #attendance\").append(\"<tr>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<td>추</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\t\"<td>가</td>\"+\r\n");
      out.write("\t\t\t\t\t\t\"</tr>\")\r\n");
      out.write("\t\t            alert(\"저장이 완료되었습니다.\"); \r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t         });  \r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
