/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-28 06:59:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<style>\r\n");
      out.write("   #page-container {\r\n");
      out.write("     position: relative;\r\n");
      out.write("     min-height: 13vh;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #content-wrap {\r\n");
      out.write("     padding-bottom: 2.5rem;    /* Footer height */\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #footer {\r\n");
      out.write("     position: sticky;\r\n");
      out.write("     bottom: 0;\r\n");
      out.write("     width: 100%;\r\n");
      out.write("     /* height: 2.5rem;  */           /* Footer height */\r\n");
      out.write("      height: 250px;\r\n");
      out.write("      background: #262A2D;\r\n");
      out.write("      color: #F6F6F6;\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      border: 1px solid blue;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .footerDiv li{\r\n");
      out.write("      list-style:none;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   #footerImg{\r\n");
      out.write("      float: right;\r\n");
      out.write("       margin: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   .footerDiv{\r\n");
      out.write("      background: #262A2D; \r\n");
      out.write("      /* background: grey; */\r\n");
      out.write("      color: #F6F6F6;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      bottom: 40px;\r\n");
      out.write("      left: 0px; \r\n");
      out.write("      border: 1px solid red;\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("    .footerDiv2{\r\n");
      out.write("    \r\n");
      out.write("      background: #262A2D; \r\n");
      out.write("      /* background: grey; */\r\n");
      out.write("      color: #F6F6F6;\r\n");
      out.write("      font-size: 12px;\r\n");
      out.write("      position: absolute;\r\n");
      out.write("      right: 0px;\r\n");
      out.write("      bottom:40px; \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #img1{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("   }\r\n");
      out.write("   #img2{\r\n");
      out.write("      width: 50px;\r\n");
      out.write("   }\r\n");
      out.write("   #img1:hover{\r\n");
      out.write("      background: red;\r\n");
      out.write("   }\r\n");
      out.write("   #img2:hover{\r\n");
      out.write("      background: red;\r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   .li1{\r\n");
      out.write("        font-size: 17px;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("   $(\"#img1\").click(function() {\r\n");
      out.write("      alert(\"ds\");\r\n");
      out.write("      $(this).css({\"background\":\"red\"});\r\n");
      out.write("   });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>footer test</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div id=\"page-container\">\r\n");
      out.write(" <!--    <div id=\"content-wrap\">\r\n");
      out.write("    </div> -->\r\n");
      out.write("    <footer id=\"footer\">\r\n");
      out.write("   <!--    <div class= footerTitle><h3>KH Groupware</h3></div> -->\r\n");
      out.write("         <!-- <div style=\"height: 5px\"></div> -->\r\n");
      out.write("         &nbsp;&nbsp;\r\n");
      out.write("         <div class=footerDiv style=\"width: 1480px; height:180px; display: inline-block;\">\r\n");
      out.write("         \t　\r\n");
      out.write("            <ul>\r\n");
      out.write("               <li><h1 style=\"text-align: left;height: 77px;\">KH Groupware</h1></li>\r\n");
      out.write("               <li class=\"li1\">| SEMI-5조 | 이거사조 | 강현모, 안상재, 이준배, 조호관 |</li>\r\n");
      out.write("               <li class=\"li1\">  주소: 서울특별시 강남구 테헤란로14길 6 남도빌딩 5F S반 </li>\r\n");
      out.write("               <li class=\"li1\">Copyright 2019. 이거사조. ALL RIGHTS RESERVED</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("            \r\n");
      out.write("\t\t\t    \r\n");
      out.write("         </div>\r\n");
      out.write("     &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("            <div class=\"footerDiv2\" style=\"width: 355px; height:180px;display: inline-block;\">\r\n");
      out.write("            　\r\n");
      out.write("             <ul style=\"font-size: 20px;\">\r\n");
      out.write("               <li><h3 style=\"text-align-last: center;\">CLICK BUTTON!</h3></li>\r\n");
      out.write("               <li style=\"text-align: center; height: 50px;\">-----------------</li>\r\n");
      out.write("               <li style=\"text-align: center; height: 50px;\">Alliance With</li>\r\n");
      out.write("               <li target=\"_blank\" style=\"text-align-last: center;\">\r\n");
      out.write("                  <img id=\"img1\" src =\"");
      out.print(request.getContextPath() );
      out.write("/images/icon/KH.png\"  onclick=\"location.href='https://iei.or.kr/main/main.kh'\">\r\n");
      out.write("                  <img id=\"img2\" src =\"");
      out.print(request.getContextPath() );
      out.write("/images/icon/HRD.png\" onclick=\"location.href='http://hrd.go.kr/hrdp/ma/pmmao/indexNew.do'\">\r\n");
      out.write("               </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("         </div>\r\n");
      out.write("   </footer>\r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
