/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-20 16:06:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import member.model.vo.khClass;

public final class backup_005fjoin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.khClass");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");


	ArrayList<khClass> cList = (ArrayList)request.getAttribute("class");


      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/bPopup/0.11.0/jquery.bpopup.js'></script>\r\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/bPopup/0.11.0/jquery.bpopup.min.js'></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("\t.outer{\r\n");
      out.write("\t\t/* border: 2px solid black; */ \r\n");
      out.write("\t\twidth : 90%;\r\n");
      out.write("\t\theight : 500px;\r\n");
      out.write("\t\tbackground : white;\r\n");
      out.write("\t\tcolor : black;\r\n");
      out.write("\t\tmargin-left : 5%;\r\n");
      out.write("\t\tmargin-right : 5%;\r\n");
      out.write("\t\tmargin-top : 3%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.outer label, .outer td{\r\n");
      out.write("\t\tcolor : black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#joinForm{\r\n");
      out.write("\t\tmargin-top: 40px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\tinput{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tmargin-top : 2px;\r\n");
      out.write("\t\twidth: 600px;\r\n");
      out.write("\t\theight: 30px;\r\n");
      out.write("\t\tmargin-left: 50px;\r\n");
      out.write("\t\tmargin-right: 60px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#idCheck, #joinBtn{\r\n");
      out.write("\t\tmargin-top: 2px;\r\n");
      out.write("\t\tbackground : black;\r\n");
      out.write("\t\tcolor : white;\r\n");
      out.write("\t\tborder-radius : 5px;\r\n");
      out.write("\t\twidth : 150px;\r\n");
      out.write("\t\theight : 40px;\r\n");
      out.write("\t\ttext-align : center;\r\n");
      out.write("\t}\r\n");
      out.write("\tth{\r\n");
      out.write("\t\tbackground : red;\r\n");
      out.write("\t}\r\n");
      out.write("\ttd{\r\n");
      out.write("\t\tfont-size: 22px;\r\n");
      out.write("\t\ttext-align : right;\r\n");
      out.write("\t\theight: 70px;\r\n");
      out.write("\t\tbackground : blue;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tselect{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\twidth: 600px;\r\n");
      out.write("\t\tmargin-left: 100px;\r\n");
      out.write("\t\tmargin-right: 63px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#joinForm tr{\r\n");
      out.write("\t\tmargin-bottom: 40px;\r\n");
      out.write("\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#goMain{\r\n");
      out.write("\t\tbackground : white;\r\n");
      out.write("\t\tcolor : black;\r\n");
      out.write("\t\tborder-radius : 5px;\r\n");
      out.write("\t\twidth : 150px;\r\n");
      out.write("\t\theight : 40px;\r\n");
      out.write("\t\ttext-align : center;\r\n");
      out.write("\t\tborder: 1px solid black;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#joinBtn, #goMain{\r\n");
      out.write("\t\tdisplay : inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btns{\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tpadding: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#idCheckPop{\r\n");
      out.write("\t\twidth:\t500px;\r\n");
      out.write("\t\theight: 200px; \r\n");
      out.write("\t\tdisplay: none;\r\n");
      out.write("\t\tbackground: white;\r\n");
      out.write("\t\tpadding: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<header>\r\n");
      out.write("\t\r\n");
      out.write("</header>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- menubar.jsp를 찾아서 그 페이지를 내 페이지에 include(포함)시켜라 // 페이지에서 사용한 스크립트,css 모두다 가져옴-->\r\n");
      out.write("\r\n");
      out.write("<div class = \"outer\">\r\n");
      out.write("\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<h1 align=\"left\" style=\"font-size : 50px;\"><em>회원가입</em></h1>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<form id = \"joinForm\" action = \"");
      out.print(request.getContextPath() );
      out.write("/insert.me\" method =\"post\" >\r\n");
      out.write("\t\t\t<table align = \"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th width =\"200px\"> * 아이디 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" maxlength =\"13\" name = \"userId\" required></td>  <!--required 미입력시 값을 입력하세요 문구뜸  -->\r\n");
      out.write("\t\t\t\t\t<td width =\"200px\"><div id=\"idCheck\" class = \"btns\"\">중복확인</div></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr></tr><tr></tr><tr></tr><tr></tr><tr></tr><tr></tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 비밀번호 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type =\"password\" maxlength=\"13\" name =\"userPwd\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>* 비밀번호 확인</th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"password\" maxlength=\"13\" name=\"userPwd2\" required></td>\r\n");
      out.write("\t\t\t\t\t<td><label id =\"pwdResult\"></label></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 이름 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" maxlength=\"5\" name=\"userName\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 주민등록번호 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" maxlength=\"5\" name=\"userRRN\" required></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 연락처 </th>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<input type=\"tel\" maxlength=\"11\" name=\"phone\" placeholder=\"(-없이)01012345678\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 이메일 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"email\" name = \"email\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 주소 </th>\r\n");
      out.write("\t\t\t\t\t<td><input type=\"text\" name = \"address\"></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th> * 반 </th>\r\n");
      out.write("\t\t\t\t\t<td><select name = \"class\">\r\n");
      out.write("\t\t\t\t\t");
for(int i = 0 ; i < cList.size(); i++ ){ 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value = \"");
      out.print(cList.get(i).getcId());
      out.write('"');
      out.write('>');
      out.print(cList.get(i).getcName() );
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
 }
      out.write(" \r\n");
      out.write("\t\t\t\t\t</select></td>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div  align = \"right\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- submit 방법 1 (함수활용해서 submit하기 )(required동작 안함) -->\r\n");
      out.write("\t\t\t\t<div class = \"btns\" id = \"joinBtn\" onclick = \"insertMember();\">가입하기</div> <!--함수방식은 required 적용이안됨-->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- submit 방법 2 -->\r\n");
      out.write("\t\t\t\t<!-- <input id = \"joinBtn\" type=\"submit\" value =\"가입하기\">\t -->\t\t\t<!-- submit버튼으로 만들어서 실행해야 input태그들의 required이 발동함 -->\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<!-- InsertMemberServlet 만들러 감 -->\r\n");
      out.write("\t\t\t\t<div class = \"btns\" id = \"goMain\" onclick = \"goMain();\">메인으로</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 중복체크 팝업창 -->\r\n");
      out.write("\t<div id = \"idCheckPop\">\r\n");
      out.write("\t\t\t<h1>test</h1>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 메인으로 이동 함수\r\n");
      out.write("\t\tfunction goMain(){\r\n");
      out.write("\t\t\tlocation.href =\"");
      out.print(request.getContextPath());
      out.write("/index.jsp\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 회원가입 하기 함수\r\n");
      out.write("\t\tfunction insertMember(){\r\n");
      out.write("\t\t\t// submit은 div가 아니라 form에서 해줘야함\r\n");
      out.write("\t\t\t$(\"#joinForm\").submit();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".btns\").hover(function() {\r\n");
      out.write("\t\t\t  $(this).css({\"cursor\": \"pointer\"});\r\n");
      out.write("\t\t\t}, function(){\r\n");
      out.write("\t\t\t //$(this).css({\"background\":\"black\"})\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(function() {\r\n");
      out.write("\t\t\tvar BPOPUP = '';\r\n");
      out.write("\t\t\t$('#idCheck').on('click', function(e) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\tBPOPUP = $('#idCheckPop').bPopup({\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
