/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-24 14:53:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class findIdPwd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<script\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.emailjs.com/sdk/2.3.2/email.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t#outer{\r\n");
      out.write("\t\t/* border: 3px solid black; */\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t#findId{\r\n");
      out.write("\t\t/* border: 3px solid black; */\r\n");
      out.write("\t\tbackground: whitesmoke;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t\tmargin: 4%;\r\n");
      out.write("\t\tmargin-left: 5%;\r\n");
      out.write("\t\tmargin: 5%;\r\n");
      out.write("\t\tmargin-top: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#findPwd{\r\n");
      out.write("\t\t/* border: 3px solid black; */\r\n");
      out.write("\t\tbackground: whitesmoke;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\twidth: 40%;\r\n");
      out.write("\t\tmargin: 4%;\r\n");
      out.write("\t\tmargin-top: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.btn{\r\n");
      out.write("\t\twidth : 10%;\r\n");
      out.write("\t\tmargin-top: 50px;\r\n");
      out.write("\t\tmargin-left: 45%;\r\n");
      out.write("\t\tmargin-right: 45%;\r\n");
      out.write("\t\twidth: 100px;\r\n");
      out.write("\t\theight: 40px;\r\n");
      out.write("\t\tcolor: white;\r\n");
      out.write("\t\tbackground: black;\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.btn:hover{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t\tbackground: grey;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.label{\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t\tpadding-right: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttd, th{\r\n");
      out.write("\t\tpadding-top: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tinput, select{\r\n");
      out.write("\t\tborder: 0px solid whitesmoke;\r\n");
      out.write("\t\tfont-size: 15px;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id = \"outer\">\r\n");
      out.write("\t\t<h1 style = \"font-size: 40px;\"><em>아이디/비밀번호 찾기</em></h1><br><br><br><br><br>\r\n");
      out.write("\t\t<div id = \"findId\">\r\n");
      out.write("\t\t\t<h2 style = \"margin-left: 15px;\">아이디 찾기</h2>\r\n");
      out.write("\t\t\t<table id = \"idTable\" align = \"center\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class = \"label\">이름</td>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" id = \"nameI\" style = \"width: 100px; height: 30px;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class = \"label\">이메일</td>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" id = \"emailPtI\" name = \"emailId\" style=\"width: 100px; height: 30px; margin-right: 5px;\" required=\"required\"><em>@</em>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id = \"email2I\" name=\"email2I\" value=\"naver.com\" style=\"width: 130px; height: 30px; margin-left: 0px;\" ReadOnly=\"true\" placeholder = \"naver.com\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<th>\r\n");
      out.write("\t\t\t\t\t<select id = \"selctEmailI\" name = \"selctEmail\" class = \"info\" style=\"width: 110px; margin-left: 3px; height: 36px;\" onchange=\"SetEmailTailI(selctEmailI.options[this.selectedIndex].value)\" >\r\n");
      out.write("\t\t\t\t\t\t<!-- <option value = \"notSelected\">====선택====</option> -->\r\n");
      out.write("\t\t\t\t\t\t<option value = \"naver.com\">naver.com</option> \r\n");
      out.write("\t\t\t\t\t\t<option value = \"goole.com\">google.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"yahoo.com\">yahoo.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"nate\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"hotmail.com\">hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"etc\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td id = \"infoI\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<button id = \"idBtn\" class = \"btn\" onclick=\"sendEmail('id')\">확인하기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id = \"findPwd\">\r\n");
      out.write("\t\t\t<h2 style = \"margin-left: 15px;\">비밀번호 찾기</h2>\r\n");
      out.write("\t\t\t<table id = \"pwdTable\" align = \"center\" >\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class = \"label\">아이디</td>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" id = \"idP\" style = \"width: 100px; height: 30px;\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class = \"label\">이메일</td>\r\n");
      out.write("\t\t\t\t\t<td><input type = \"text\" id = \"emailPtP\" name = \"emailId\" style=\"width: 100px; height: 30px; margin-right: 5px;\" required=\"required\"><em>@</em>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"email2P\" name=\"email2P\" value=\"naver.com\" style=\"width: 130px; height: 30px; margin-left: 0px;\" ReadOnly=\"true\" placeholder = \"naver.com\">\r\n");
      out.write("\t\t\t\t\t<select id = \"selctEmailP\" name = \"selctEmail\" class = \"info\" style=\"width: 110px; margin-left: 3px; height: 36px;\" onchange=\"SetEmailTailP(selctEmailP.options[this.selectedIndex].value)\" >\r\n");
      out.write("\t\t\t\t\t\t<!-- <option value = \"notSelected\">====선택====</option> -->\r\n");
      out.write("\t\t\t\t\t\t<option value = \"naver.com\">naver.com</option> \r\n");
      out.write("\t\t\t\t\t\t<option value = \"goole.com\">google.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"hanmail.net\">hanmail.net</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"yahoo.com\">yahoo.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"nate\">nate.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"hotmail.com\">hotmail.com</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"daum.net\">daum.net</option>\r\n");
      out.write("\t\t\t\t\t\t<option value = \"etc\">직접입력</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td class = \"label\">전화번호</td>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<select id = \"tel0\" class = \"phone\" name = \"phone1\" style=\"width: 90px; margin-left: 0px; height: 36px;\">\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"010\">010</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"011\">011</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"016\">016</option>\r\n");
      out.write("\t\t\t\t\t\t\t<option value = \"019\">019</option>\r\n");
      out.write("\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t<input id = \"tel1\" class = \"phone\" type=\"tel\" maxlength=\"4\" name=\"phone2\" style=\"width: 100px; height: 30px; margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t\t\t<input id = \"tel2\" class = \"phone\" type=\"tel\" maxlength=\"4\" name=\"phone3\" style=\"width: 100px; height: 30px;  margin-left: 5px;\">\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t<td id =\"infoP\"></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t\t<button id = \"pwdBtn\" class = \"btn\" onclick=\"sendEmail('pwd')\">확인하기</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("function SetEmailTailI(emailValue) {\r\n");
      out.write("\t  var email = document.all(\"email\")    // 사용자 입력\r\n");
      out.write("\t  var emailTail = document.all(\"email2I\") // Select box\r\n");
      out.write("\t  \r\n");
      out.write("\t  if ( emailValue == \"notSelected\" )\r\n");
      out.write("\t   return;\r\n");
      out.write("\t  else if ( emailValue == \"etc\" ) {\r\n");
      out.write("\t   emailTail.placeholder = \"\";\r\n");
      out.write("\t   emailTail.readOnly = false;\r\n");
      out.write("\t   emailTail.value = \"\";\r\n");
      out.write("\t   emailTail.focus();\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t   emailTail.readOnly = true;\r\n");
      out.write("\t   emailTail.value = emailValue;\r\n");
      out.write("\t  }\r\n");
      out.write("\t }\r\n");
      out.write("function SetEmailTailP(emailValue) {\r\n");
      out.write("\t  var email = document.all(\"email\")    \r\n");
      out.write("\t  var emailTail = document.all(\"email2P\") \r\n");
      out.write("\t  \r\n");
      out.write("\t  if ( emailValue == \"notSelected\" )\r\n");
      out.write("\t   return;\r\n");
      out.write("\t  else if ( emailValue == \"etc\" ) {\r\n");
      out.write("\t   emailTail.placeholder = \"\";\r\n");
      out.write("\t   emailTail.readOnly = false;\r\n");
      out.write("\t   emailTail.value = \"\";\r\n");
      out.write("\t   emailTail.focus();\r\n");
      out.write("\t  } else {\r\n");
      out.write("\t   emailTail.readOnly = true;\r\n");
      out.write("\t   emailTail.value = emailValue;\r\n");
      out.write("\t  }\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("id = null; \r\n");
      out.write("pwd = null;\r\n");
      out.write("flag = false;\r\n");
      out.write("function sendEmail(idOrPwd){\r\n");
      out.write("\r\n");
      out.write("\tif(idOrPwd == \"id\"){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl:\"/KH_Groupware/findId.me\",\r\n");
      out.write("\t\t\tdata:{\r\n");
      out.write("\t\t\t\tuserName : $(\"#nameI\").val(),\r\n");
      out.write("\t\t\t\temailId : $(\"#emailPtI\").val(),\r\n");
      out.write("\t\t\t\temailTail : $(\"#email2I\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif(data == null){\r\n");
      out.write("\t\t\t\t\t$(\"#infoI\").html(\"일치하는 정보가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#infoI\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#infoI\").html(\"아이디를 이메일로 전송하였습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#infoI\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t\tid = data;\r\n");
      out.write("\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\tif(idOrPwd == \"pwd\"){\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : \"/KH_Groupware/findPwd.me\",\r\n");
      out.write("\t\t\tdata : {\r\n");
      out.write("\t\t\t\tuserId : $(\"#idP\").val(),\r\n");
      out.write("\t\t\t\temailId : $(\"#emailPtP\").val(),\r\n");
      out.write("\t\t\t\temailTail : $(\"#email2P\").val(),\r\n");
      out.write("\t\t\t\ttel0 : $(\"#tel0\").val(),\r\n");
      out.write("\t\t\t\ttel1 : $(\"#tel1\").val(),\r\n");
      out.write("\t\t\t\ttel2 : $(\"#tel2\").val()\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif(data == 0){\r\n");
      out.write("\t\t\t\t\t$(\"#infoP\").html(\"일치하는 정보가 없습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#infoP\").css(\"color\", \"red\");\r\n");
      out.write("\t\t\t\t\tflag = false;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$(\"#infoP\").html(\"임시비밀번호를 이메일로 전송하였습니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#infoP\").css(\"color\", \"blue\");\r\n");
      out.write("\t\t\t\t\tpwd = data;\r\n");
      out.write("\t\t\t\t\tflag = true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tif (flag == true) {\r\n");
      out.write("\t\t\t(function() {\r\n");
      out.write("\t\t\t\tif (idOrPwd == \"id\") {\r\n");
      out.write("\t\t\t\t\tvar emailC = {\r\n");
      out.write("\t\t\t\t\t\tcontents : \"찾으시는 아이디는 '\" + id + \"'입니다.\",\r\n");
      out.write("\t\t\t\t\t\tuserEmail : $(\"#emailPtI\").val() + \"@\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ $(\"#email2I\").val()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else if (idOrPwd == \"pwd\") {\r\n");
      out.write("\t\t\t\t\tvar emailC = {\r\n");
      out.write("\t\t\t\t\t\tcontents : \"임시비밀번호는 '\" + pwd + \"'입니다.\",\r\n");
      out.write("\t\t\t\t\t\tuserEmail : $(\"#emailPtP\").val() + \"@\"\r\n");
      out.write("\t\t\t\t\t\t\t\t+ $(\"#email2P\").val()\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\temailjs.init(\"user_1Xuzxxg4iKutLXCbWcLL9\");\r\n");
      out.write("\t\t\t\temailjs.send(\"asdhyoo@gmail.com\", \"template_k2P6Sw73\", emailC)\r\n");
      out.write("\t\t\t\t\t\t.then(\r\n");
      out.write("\t\t\t\t\t\t\t\tfunction(response) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"SUCCESS. status=%d, text=%s\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\tresponse.status, response.text);\r\n");
      out.write("\t\t\t\t\t\t\t\t}, function(err) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(\"FAILED. error=\", err);\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("\t\t\t})();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
>>>>>>> refs/remotes/origin/master
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
