/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-10-25 11:32:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import member.model.vo.Member;

public final class infoPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/views/common/header.jsp", Long.valueOf(1571997394980L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<style>\r\n");
      out.write(".container {\r\n");
      out.write("  border: 2px solid #ccc;\r\n");
      out.write("  background-color: #eee;\r\n");
      out.write("  border-radius: 5px;\r\n");
      out.write("  padding: 16px;\r\n");
      out.write("  margin: 16px 0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container::after {\r\n");
      out.write("  content: \"\";\r\n");
      out.write("  clear: both;\r\n");
      out.write("  display: table;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container img {\r\n");
      out.write("  float: left;\r\n");
      out.write("  margin-right: 20px;\r\n");
      out.write("  border-radius: 50%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container span {\r\n");
      out.write("  font-size: 20px;\r\n");
      out.write("  margin-right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 500px) {\r\n");
      out.write("  .container {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("  }\r\n");
      out.write("  .container img {\r\n");
      out.write("      margin: auto;\r\n");
      out.write("      float: none;\r\n");
      out.write("      display: block;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("    \r\n");

   Member loginUser = (Member)session.getAttribute("loginUser");

   int userNo = 0; 
   if(loginUser != null){
      userNo = loginUser.getUserNo();
   } 



      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("\r\n");
      out.write("<!-- 지워야함 쓰려면 메인홈에서 제이쿼리 적용해서 써야함. -->\r\n");
      out.write("<!-- <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src = \"../js/jquery-3.2.1.min.js\" type = \"text/javascript\"></script> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>KH_Groupware</title>\r\n");
      out.write("\r\n");
      out.write("<!--  모두 파비콘을 가져가서 본인 파일에 삽입해주세요  -->\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image⁄x-icon\" href=\"../../images/KH_favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800&display=swap&subset=korean\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Do+Hyeon&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("   /* place holder 감추기*/\r\n");
      out.write("   input:focus::-webkit-input-placeholder, textarea:focus::-webkit-input-placeholder { /* WebKit browsers */ color:transparent; } \r\n");
      out.write("   input:focus:-moz-placeholder, textarea:focus:-moz-placeholder { /* Mozilla Firefox 4 to 18 */ color:transparent; } \r\n");
      out.write("   input:focus::-moz-placeholder, textarea:focus::-moz-placeholder { /* Mozilla Firefox 19+ */ color:transparent; } \r\n");
      out.write("   input:focus:-ms-input-placeholder, textarea:focus:-ms-input-placeholder { /* Internet Explorer 10+ */ color:transparent; }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* @font-face {\r\n");
      out.write("   font-family: 'Noto Sans KR', sans-serif;\r\n");
      out.write("} */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("#menuBar{\r\n");
      out.write("   display:block;\r\n");
      out.write("   width:100%;\r\n");
      out.write("   height: 65px;\r\n");
      out.write("   border:none;\r\n");
      out.write("   box-sizing:border-box;\r\n");
      out.write("   vertical-align:middle;\r\n");
      out.write("   padding-left: 15px;\r\n");
      out.write("   padding-right: 15px;\r\n");
      out.write("   line-height:  60px;\r\n");
      out.write("   background-color: #262A2D; /*#353535*/\r\n");
      out.write("   border-bottom: 0;\r\n");
      out.write("   box-shadow: 0px 1px 3px rgba(0,0,0,0.3);\r\n");
      out.write("   z-index: 9999;\r\n");
      out.write("   margin:0;\r\n");
      out.write("   list-style:none;\r\n");
      out.write("   left:0;\r\n");
      out.write("   top:0;\r\n");
      out.write("   position:fixed;\r\n");
      out.write("   color: #F6F6F6;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".menu{\r\n");
      out.write("   position: abolute;\r\n");
      out.write("   width: 10%;\r\n");
      out.write("   height: 65px;\r\n");
      out.write("   display: table-cell;\r\n");
      out.write("   text-align: center;\r\n");
      out.write("   z-index: 0px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   font-size: 16px;\r\n");
      out.write("   font-family:\"Nanum Gothic\"\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#logo{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".logoImg{\r\n");
      out.write("   position: relative;\r\n");
      out.write("   float: left;\r\n");
      out.write("   width: 230px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menu:hover{\r\n");
      out.write("   color: #343434;\r\n");
      out.write("   font-weight: 800;\r\n");
      out.write("   cursor: pointer;\r\n");
      out.write("   background: #fcfaf1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".memberMenu:hover{\r\n");
      out.write("\r\n");
      out.write("   background: none;\r\n");
      out.write("   color: #fcfaf1;\r\n");
      out.write("    transition-duration: 0.3s;\r\n");
      out.write("}\r\n");
      out.write(".iconSpan{\r\n");
      out.write("   height: 65px;\r\n");
      out.write("   padding: 2px;\r\n");
      out.write("   padding-left:6px; \r\n");
      out.write("   padding-right: 6px;\r\n");
      out.write("   z-index: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".iconSpan:hover{\r\n");
      out.write("    background: #fcfaf1;\r\n");
      out.write("   color: #343434;\r\n");
      out.write("    transition-duration: 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".outerDiv{\r\n");
      out.write("   margin: -10px;\r\n");
      out.write("  padding:0px;\r\n");
      out.write("  z-index: 8888;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/*  body {margin:0;}; */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".subMenu{\r\n");
      out.write("   width: 100%;\r\n");
      out.write("   height: 500px;\r\n");
      out.write("   margin:0px;\r\n");
      out.write("   list-style:none;\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   vertical-align:middle;\r\n");
      out.write("   line-height:  60px;\r\n");
      out.write("      box-shadow: 0px 1px 3px rgba(0,0,0,0.3);\r\n");
      out.write("      left:0px;\r\n");
      out.write("      right: 0px;\r\n");
      out.write("      top: 44px;\r\n");
      out.write("      background: #fcfaf1;\r\n");
      out.write("    border: none;\r\n");
      out.write("   display: none;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".hoverStay{\r\n");
      out.write("   background:#fcfaf1;\r\n");
      out.write("   color: #343434;\r\n");
      out.write("   font-weight: 1000;\r\n");
      out.write("}\r\n");
      out.write(".textArea{\r\n");
      out.write("   float:left;\r\n");
      out.write("   height: 70%;\r\n");
      out.write("   width: 350px;\r\n");
      out.write("   align-text:center; \r\n");
      out.write("   vertical-align:middle;\r\n");
      out.write("   padding-top: 50px;\r\n");
      out.write("   padding-left: 20px; \r\n");
      out.write("   position: relative;\r\n");
      out.write("   font-size: 16px;\r\n");
      out.write("   font-weight: bold;\r\n");
      out.write("   font-family:\"Nanum Gothic\";\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   left: 120px;\r\n");
      out.write("   border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".textArea p{\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   padding:none;\r\n");
      out.write("   margin:none;\r\n");
      out.write("   border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".textArea p span{\r\n");
      out.write("   border:none;\r\n");
      out.write("   width: 80px;\r\n");
      out.write("   padding:none;\r\n");
      out.write("   padding-bottom:7px;\r\n");
      out.write("   margin:none;\r\n");
      out.write("   border: none;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".textArea p span:hover{\r\n");
      out.write("   color: gray;\r\n");
      out.write("   cursor:pointer;\r\n");
      out.write("   border-bottom: 2px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".imgArea{\r\n");
      out.write("   border: none;\r\n");
      out.write("   height: 100%;\r\n");
      out.write("   width: 1100px;\r\n");
      out.write("   display: inline-block;\r\n");
      out.write("   z-index: 1000;\r\n");
      out.write("   float:right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".blackOpacity{\r\n");
      out.write(" background:black;\r\n");
      out.write("   position:fixed;\r\n");
      out.write("   width:100%;\r\n");
      out.write("   height:100%;\r\n");
      out.write("   opacity: 0.8;\r\n");
      out.write("   display:none;\r\n");
      out.write("   left:0px;\r\n");
      out.write("   right:0px;\r\n");
      out.write("   z-index:3;\r\n");
      out.write("   float: bottom;\r\n");
      out.write("   top:65px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".loginDiv{\r\n");
      out.write("   background: #fcfaf1;\r\n");
      out.write("   width: 450px; \r\n");
      out.write("   height: 100%; \r\n");
      out.write("   color: black; \r\n");
      out.write("   text-align: center; \r\n");
      out.write("   margin: 0px;\r\n");
      out.write("   border: 1px solid lightgray;\r\n");
      out.write("   float: right;\r\n");
      out.write("   position:fixed; right:-620px;\r\n");
      out.write("   z-index:9998;\r\n");
      out.write("   top: 65px;\r\n");
      out.write("   display:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".loginArea{\r\n");
      out.write("width: 450px;\r\n");
      out.write("heigh: 500px;\r\n");
      out.write("border: 1px solid black;\r\n");
      out.write(" z-index: 11;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".joinArea{\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".introMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 250px;\r\n");
      out.write("}\r\n");
      out.write(".boardMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 380px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".shareMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 510px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".elbumMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 640px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".tastyMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 770px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".mypageMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 900px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".teacherMenu{\r\n");
      out.write("   position:absolute; \r\n");
      out.write("   width: 130px;\r\n");
      out.write("   left: 1030px;\r\n");
      out.write("}\r\n");
      out.write(".memberMenu{ \r\n");
      out.write("   position: absolute;\r\n");
      out.write("   right: 0px;\r\n");
      out.write("   font-size: 24px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon1{ /* 채팅*/\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   right: 105px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon2{ /*회원가입*/\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   right: 60px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".icon3{  /*로그인*/\r\n");
      out.write("   position: absolute;\r\n");
      out.write("   right: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".blackBtn{\r\n");
      out.write("   font-size: 15px;  \r\n");
      out.write("    outline: none;\r\n");
      out.write("    color: #F6F6F6;\r\n");
      out.write("    background-color: #262A2D;\r\n");
      out.write("    margin:auto;\r\n");
      out.write("    padding:auto;\r\n");
      out.write("    width: 350px;\r\n");
      out.write("    height: 50px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    border : none;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    vertical-align: middle;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blackBtn1:hover{\r\n");
      out.write("   background: #f53f29;\r\n");
      out.write("   color: white;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".blackBtn2:hover{\r\n");
      out.write("   background: #E7E3E3;\r\n");
      out.write("   color: #262A2D;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("body{ \r\n");
      out.write("   margin: 0px;\r\n");
      out.write("   overflow-x:hidden;   /*스크롤 가로  잠금*/   \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".menubarImg{\r\n");
      out.write("   height:500px;\r\n");
      out.write("   width:1100px;\r\n");
      out.write("   border:none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div id= outerDiv>;  \r\n");
      out.write("   <div id= \"menuBar\" >\r\n");
      out.write("         <div class =\"menu logoImg\">KH정보교육원사진</div>\r\n");
      out.write("         <div class= \"menu introMenu\">소개</div>\r\n");
      out.write("         <div class= \"menu boardMenu\" onclick = \"showBoardDiv();\">게시판</div>\r\n");
      out.write("         <div class= \"menu shareMenu\">공유자료</div>\r\n");
      out.write("         <div class= \"menu elbumMenu\">앨범</div>\r\n");
      out.write("         <div class= \"menu tastyMenu\">맛집</div>\r\n");
      out.write("         <div class= \"menu mypageMenu\" onclick = \"showMypageDiv();\">마이페이지</div>\r\n");
      out.write("         <div class= \"menu teacherMenu\" onclick = \"showTeacherDiv();\">강사페이지</div>\r\n");
      out.write("         <div class= \"menu memberMenu\">\r\n");
      out.write("            <span class= \"iconSpan icon1\"><i class=\"fa fa-comments\" aria-hidden=\"true\"></i></span>&nbsp;\r\n");
      out.write("            <span class= \"iconSpan icon2\"><i class=\"fa fa-sign-in\" aria-hidden=\"true\"></i></span>&nbsp;\r\n");
      out.write("            <span id= \"loginIcon\" class= \"iconSpan icon3\" onclick= \"loginDivShow();\"><i class=\"fa fa-user\" aria-hidden=\"true\" ></i></span>\r\n");
      out.write("         </div>\r\n");
      out.write("    </div>   \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   <!-- 게시판 서브메뉴 div -->\r\n");
      out.write("    <div id= \"boardDiv\" class=\"subMenu\" data-value = \"0\">\r\n");
      out.write("       <div class= textArea>\r\n");
      out.write("          <p><span>공지사항</span></p>\r\n");
      out.write("          <p><span>자유게시판</span></p>\r\n");
      out.write("          <p><span>사진게시판</span></p>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class= imgArea>\r\n");
      out.write("             <img src=\"../../images/helloquence-5fNmWej4tAA-unsplash.jpg\" class= \"menubarImg\">\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 마이페이지 서브메뉴 div -->   \r\n");
      out.write("   <div id= \"mypageDiv\" class=\"subMenu\" data-value = \"0\">\r\n");
      out.write("       <div class= textArea>\r\n");
      out.write("          <p style=\"width:130px;\"><span style=\"width:130px;\">내 정보수정<span></p>\r\n");
      out.write("          <p style=\"width:130px;\"><span style=\"width:130px;\" >일정 및 휴가관리<span></p>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class= imgArea>\r\n");
      out.write("          <img src=\"../../images/damian.jpg\" class= \"menubarImg\">\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   <!-- 강사페이지 서브메뉴 div -->   \r\n");
      out.write("   <div id= \"teacherDiv\" class=\"subMenu\" data-value = \"0\">\r\n");
      out.write("       <div class= textArea>\r\n");
      out.write("          <p>가입승인</p>\r\n");
      out.write("          <p>학생관리</p>\r\n");
      out.write("          <p>자리배치</p>\r\n");
      out.write("       </div>\r\n");
      out.write("       <div class= imgArea>\r\n");
      out.write("          <img src=\"../../images/teacherPage.jpg\" class= \"menubarImg\">\r\n");
      out.write("       </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div id= \"loginDiv\" class=\"loginDiv\" data-value = \"0\">\r\n");
      out.write("      <div class=loginArea>\r\n");
      out.write("         <div>\r\n");
      out.write("            <br><br>\r\n");
      out.write("            <span>회원이시면 로그인해주세요</span><br><br>\r\n");
      out.write("            <span>ID:</span><input type=\"text\" name = \"userId\" id = \"userId\"  placeholder=\"Enter UserId\"><br>\r\n");
      out.write("            <span>PW:</span><input type=\"text\"  name = \"userPwd\" id = \"userPwd\" placeholder=\"Enter Password\"><br> \r\n");
      out.write("            \r\n");
      out.write("            <input type = \"checkbox\" name = \"saveID\" id = \"saveId\"><label for = \"saveId\">아이디 저장하기</label><br><br>\r\n");
      out.write("            \r\n");
      out.write("            <button class = \" blackBtn blackBtn1\" type = \"submit\" onclick = \"login();\" type=\"button\">로그인</button><br><br>\r\n");
      out.write("            <button class = \"blackBtn blackBtn2\" loginBtn\" type = \"submit\" onclick = \"login();\" type=\"button\">아이디 찾기</button>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=joinArea>\r\n");
      out.write("         <div>\r\n");
      out.write("            <span>비회원이시면 가입해주세요</span>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"blackOpacity1\" class= blackOpacity></div>  <!--  게시판 -->\r\n");
      out.write("<div id=\"blackOpacity2\" class= blackOpacity></div>  <!-- 마이페이지  -->\r\n");
      out.write("<div id=\"blackOpacity3\" class= blackOpacity></div>   <!-- 강사페이지 -->\r\n");
      out.write("<div id=\"blackOpacity4\" class= blackOpacity></div>   <!-- 로그인  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("// 각각 자기 자신의 sub메뉴를 제외하고 다른 것을 눌렀을때 서브메뉴가 올라가는 메소드\r\n");
      out.write("  $('html').click(function(e){ \r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("     if( $(\"#boardDiv\").data(\"value\") ==\"1\"){ \r\n");
      out.write("      if(!$(e.target).hasClass(\"boardDown\")){  \r\n");
      out.write("         if($('#boardDiv').data(\"value\") == \"1\"){\r\n");
      out.write("            $(\"#boardDiv\").slideUp(); \r\n");
      out.write("            $(\"#boardDiv\").data(\"value\", \"0\");\r\n");
      out.write("            $('.boardMenu').removeClass(\"hoverStay\");\r\n");
      out.write("            $(\"#blackOpacity1\").fadeOut(\"fast\");\r\n");
      out.write("         }\r\n");
      out.write("      } \r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("     \r\n");
      out.write("     if( $(\"#mypageDiv\").data(\"value\") ==\"1\"){ \r\n");
      out.write("         if(!$(e.target).hasClass(\"mypageDown\")){  \r\n");
      out.write("            if($('#mypageDiv').data(\"value\") == \"1\"){\r\n");
      out.write("               $(\"#mypageDiv\").slideUp(); \r\n");
      out.write("               $(\"#mypageDiv\").data(\"value\", \"0\");\r\n");
      out.write("               $('.mypageMenu').removeClass(\"hoverStay\");\r\n");
      out.write("               $(\"#blackOpacity2\").fadeOut(\"fast\");\r\n");
      out.write("            }\r\n");
      out.write("         } \r\n");
      out.write("        }\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("     if( $(\"#teacherDiv\").data(\"value\") ==\"1\"){ \r\n");
      out.write("         if(!$(e.target).hasClass(\"teacherDown\")){  \r\n");
      out.write("            if($('#teacherDiv').data(\"value\") == \"1\"){\r\n");
      out.write("               $(\"#teacherDiv\").slideUp(); \r\n");
      out.write("               $(\"#teacherDiv\").data(\"value\", \"0\");\r\n");
      out.write("               $('.teacherMenu').removeClass(\"hoverStay\");\r\n");
      out.write("               $(\"#blackOpacity3\").fadeOut(\"fast\");\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("        }\r\n");
      out.write("  \r\n");
      out.write("     if( $(\"#loginDiv\").data(\"value\") ==\"1\"){ \r\n");
      out.write("         if(!$(e.target).hasClass(\"loginDivShow\")){  \r\n");
      out.write("            \r\n");
      out.write("            removeLoginDiv(); \r\n");
      out.write("            \r\n");
      out.write("         } \r\n");
      out.write("       }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("// 각각의 div 토글\r\n");
      out.write("   function showBoardDiv(){\r\n");
      out.write("      if($('#boardDiv').data(\"value\") == \"0\"){\r\n");
      out.write("         $('.boardMenu').addClass(\"hoverStay\"); \r\n");
      out.write("         $('.boardMenu').addClass(\"boardDown\");\r\n");
      out.write("         $('#boardDiv').addClass(\"boardDown\");\r\n");
      out.write("         $('#boardDiv').children().addClass(\"boardDown\");    \r\n");
      out.write("         $('#boardDiv').children().children().addClass(\"boardDown\");             \r\n");
      out.write("         $(\"#boardDiv\").slideDown(); \r\n");
      out.write("         $(\"#blackOpacity1\").fadeIn(\"fast\");\r\n");
      out.write("         $(\"#boardDiv\").data(\"value\", \"1\");\r\n");
      out.write("      }else{\r\n");
      out.write("         $(\"#boardDiv\").slideUp();  \r\n");
      out.write("         $(\"#boardDiv\").data(\"value\", \"0\");\r\n");
      out.write("         $('.boardMenu').removeClass(\"hoverStay\");\r\n");
      out.write("         $(\"#blackOpacity1\").fadeOut(\"fast\");\r\n");
      out.write("      }\r\n");
      out.write("   }\r\n");
      out.write("         \r\n");
      out.write("\r\n");
      out.write("   function showMypageDiv(){\r\n");
      out.write("       if($('#mypageDiv').data(\"value\") == \"0\"){\r\n");
      out.write("            $('.mypageMenu').addClass(\"hoverStay\"); \r\n");
      out.write("            $('.mypageMenu').addClass(\"mypageDown\");\r\n");
      out.write("            $('#mypageDiv').addClass(\"mypageDown\");\r\n");
      out.write("            $('#mypageDiv').children().addClass(\"mypageDown\");    \r\n");
      out.write("            $('#mypageDiv').children().children().addClass(\"mypageDown\");             \r\n");
      out.write("            $(\"#mypageDiv\").slideDown(); \r\n");
      out.write("            $(\"#mypageDiv\").data(\"value\", \"1\");\r\n");
      out.write("            $(\"#blackOpacity2\").fadeIn(\"fast\");\r\n");
      out.write("         }else{\r\n");
      out.write("            $(\"#mypageDiv\").slideUp();  \r\n");
      out.write("            $(\"#TeacherDiv\").data(\"value\", \"0\");\r\n");
      out.write("            $('.mypageMenu').removeClass(\"hoverStay\");\r\n");
      out.write("            $(\"#blackOpacity2\").fadeOut(\"fast\");\r\n");
      out.write("         }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   function showTeacherDiv(){\r\n");
      out.write("       if($('#teacherDiv').data(\"value\") == \"0\"){\r\n");
      out.write("            $('.teacherMenu').addClass(\"hoverStay\");\r\n");
      out.write("            $('.teacherMenu').addClass(\"teacherDown\");\r\n");
      out.write("            $('#teacherDiv').addClass(\"teacherDown\");\r\n");
      out.write("            $('#teacherDiv').children().addClass(\"teacherDown\");    \r\n");
      out.write("            $('#teacherDiv').children().children().addClass(\"teacherDown\");             \r\n");
      out.write("            $(\"#teacherDiv\").slideDown(); \r\n");
      out.write("            $(\"#teacherDiv\").data(\"value\", \"1\");\r\n");
      out.write("            $(\"#blackOpacity3\").fadeIn(\"fast\");\r\n");
      out.write("            \r\n");
      out.write("         }else{\r\n");
      out.write("            $(\"#teacherDiv\").slideUp();  \r\n");
      out.write("            $(\"#teacherDiv\").data(\"value\", \"0\");\r\n");
      out.write("            $('.teacherMenu').removeClass(\"hoverStay\");\r\n");
      out.write("            $(\"#blackOpacity3\").fadeOut(\"fast\");\r\n");
      out.write("         }\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   function loginDivShow(){\r\n");
      out.write("        if($('#loginDiv').data(\"value\") == \"0\"){\r\n");
      out.write("           $('#loginIcon').addClass(\"hoverStay\");      \r\n");
      out.write("           $(\".loginDiv\").css(\"display\",\"block\")\r\n");
      out.write("           $(\"#loginIcon\").addClass(\"loginDivShow\");\r\n");
      out.write("           $(\".loginDiv\").addClass(\"loginDivShow\");\r\n");
      out.write("           $(\".loginDiv\").children().addClass(\"loginDivShow\");\r\n");
      out.write("           $(\".loginDiv\").children().children().addClass(\"loginDivShow\");\r\n");
      out.write("           $(\".loginDiv\").children().children().children().addClass(\"loginDivShow\");\r\n");
      out.write("           $(\"#blackOpacity4\").fadeIn('2000');\r\n");
      out.write("           $(\".loginDiv\").animate({\"right\":\"0px\"},'2000',function(){\r\n");
      out.write("           $(\"#loginDiv\").data(\"value\",\"1\"); \r\n");
      out.write("           }); \r\n");
      out.write("        }else{\r\n");
      out.write("             $(\"#blackOpacity2\").fadeOut('2000');\r\n");
      out.write("              $(\".loginDiv\").animate({\"right\":\"-605px\"},'2000',function(){\r\n");
      out.write("                 $(\".loginDiv\").css(\"display\",\"none\") \r\n");
      out.write("              });\r\n");
      out.write("              $(\"#blackOpacity4\").fadeOut('2000');   \r\n");
      out.write("              $(\"#loginDiv\").data(\"value\",\"0\");\r\n");
      out.write("              $(\"#loginIcon\").removeClass(\"hoverStay\") \r\n");
      out.write("        } \r\n");
      out.write("      \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("     //로그인 div 제거 \r\n");
      out.write("    function removeLoginDiv(){\r\n");
      out.write("       $(\"#blackOpacity2\").fadeOut('2000');\r\n");
      out.write("       $(\".loginDiv\").animate({\"right\":\"-605px\"},'2000',function(){\r\n");
      out.write("          $(\".loginDiv\").css(\"display\",\"none\") \r\n");
      out.write("       });\r\n");
      out.write("       $(\"#blackOpacity4\").fadeOut('2000');\r\n");
      out.write("       $(\"#loginDiv\").data(\"value\",\"0\");\r\n");
      out.write("       $(\"#loginIcon\").removeClass(\"hoverStay\")\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<h2> 정보교육원 내에서 각 반별로 실제 활용할 수 있는 웹 사이트를 개KH 발한다 본 프로젝트는 강사 간 교육생 교육생 간 교육생의 기본적인 . \r\n");
      out.write("\t    그룹웨어 및 클라우드 서비스를 제공하는 것을 목표로 한다. </h2>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<br><br>\r\n");
      out.write("<h2> 5조 소개</h2>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <img src=\"../../images/bandmember.jpg\" alt=\"Avatar\" style=\"width:90px\">\r\n");
      out.write("  <p><span>조 호 관</span> 조 장</p>\r\n");
      out.write("  <p> 공지사항 / 자유게시판 구현</p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <img src=\"../../images/jb.jpg\"\" alt=\"Avatar\" style=\"width:130px; height:130px;\"><br>\r\n");
      out.write("  <p><span>이 준 배 </span> 조 원 </p>\r\n");
      out.write("  <p> 사진 게시판 / 자료실 구현 </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <img src=\"../../images/bandmember.jpg\"\" alt=\"Avatar\" style=\"width:90px\">\r\n");
      out.write("  <p><span>강 현 모</span> 조 원</p>\r\n");
      out.write("  <p> 회원가입 / 로그인 / 가입승인 / 학생관리 / 자리배치 구현 </p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("  <img src=\"../../images/bandmember.jpg\"\" alt=\"Avatar\" style=\"width:90px\">\r\n");
      out.write("  <p><span>안 상 재</span> 조 원</p>\r\n");
      out.write("  <p> 맛집 / 채팅 구현 </p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
